### ISSUE TITLE
Add MAME support

### ISSUE THREAD

**Issue by sgtstadanko** [sselph/scraper#1]
Hey.  Great utility! I have used this on my retropie to scrape my snes and 2600 roms flawlessly.  I am having issues with mame roms.  It fails on all of them either on the hash check with gamesdb or "no valid roms found in this zip" Not sure if this is a file name structure issue and a romset issue. It looks like from the error that scraper is actually looking in the zip file for data.  all the mame roms are 0.37b5.  Here is a snippet of the errors:

2014/12/08 17:21:13 INFO: Starting: dkong.zip
2014/12/08 17:21:13 ERR: error processing dkong.zip: No valid roms found in zip.

Any ideas? Worked great on snes and 2600 roms.

**Comment by sur0x** [comment]
@sgtstadanko I've managed to get 2.138 images from the mam4all working set(2.270 roms) here:

http://www.gotmame.com/files/snap/<filename>.png

just use clrmamepro with mame4all dat file get the game list then do some script to get the files from the website, that was the cheap solution for me.

(Emumovies has around 1.800 imgs only)

**Comment by sselph** [comment]
Yeah getting the mapping of filename, human readable name, image seems like it could be done fairly easily and this might be a good start. I think people would like to have the full set of metadata like thegamesdb has so maybe pull from that when available then fallback to the basic name, image when it isn't.

**Comment by sur0x** [comment]
@sselph yeah, would be awesome to have all metadata for MAME/FBA

**Comment by sselph** [comment]
I've added a mame scraper that is pulling from mamedb. @sgtstadanko let me know how that works.

**Comment by sselph** [comment]
Forgot to mention you have to provide the -mame flag to trigger the new logic.

**Comment by sgtstadanko** [comment]
thanks! Ran it remotely and terminal results look good.  Will check UI when I get home.

**Comment by krcroft** [comment]
@sgtstadanko, @sselph - does the -mame flag need anything special?
I'm using the master sselph branch (as o this comment) to scrape the mame roms in my mame-libretro, fba, and neogeo folders (all zips freshly deposited by clrmamepro), and the scraper reports hash not found for all the zips. 
This happens regardless if I use the -mame flag or not.

**Comment by MichaelRPowell** [comment]
@krcroft sounds like an improper match for what is in the database.

Which romset did you build with clrmamepro?

**Comment by ifdiaz** [comment]
Hash not found error for all the mame/fba games. It only works on older versions of the sript (maybe because uses different database?)
