### ISSUE TITLE
Add Gzip Support (A2600)

### ISSUE THREAD

**Issue by dcteal** [sselph/scraper#10]
Whenever I try to run the scraper tool in RetroPie, I receive the following and it does go get any info - 

pi@raspberrypi ~/RetroPie/roms/atari2600 $ ./scraper -thumb_only
2015/01/05 01:14:12 INFO: Checking for new hash.csv.
2015/01/05 01:14:16 INFO: hash.csv "4a026fa21c5ec19cfd43e88e57b6e76d" up to date.

Does the scraper not work with .a26 files?  I thought it indicated in the read me file that it does support Atari 2600 files. 

Thanks for your great work!

**Comment by sur0x** [comment]
dcteal try to specify the room folder / image folder and another name/location for gamelist.xml, I think the script thinks that gamelist is already up to date.

**Comment by sselph** [comment]
Hmm for some reason I thought it only supported .bin and .zip but looks like it also supports .a26, .rom and .gz so I'll look into adding those extensions as well. a26 and rom are trivial gz will be slightly harder.

**Comment by sselph** [comment]
Added a26 and rom extensions. I'll work on gzip support when I have time.

**Comment by sselph** [comment]
Added Gzip support.
