### ISSUE TITLE
Crash during a scrape of a SegaCD Directory

### ISSUE THREAD

**Issue by gimmer** [sselph/scraper#101]
I have a rather large directory of games.

When I run the scraper it crashes.

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x24 pc=0x4a454e]

goroutine 1 [running]:
panic(0x845ea0, 0x10f6a030)
        C:/Go/src/runtime/panic.go:481 +0x326
github.com/sselph/scraper/rom.exists(0x122acba0, 0x5e, 0x2)
        C:/Go/projects/src/github.com/sselph/scraper/rom/rom.go:352 +0x6e
github.com/sselph/scraper/rom.(*ROM).populateBins(0x122d0e80, 0x0, 0x0)
        C:/Go/projects/src/github.com/sselph/scraper/rom/rom.go:194 +0xa8b
github.com/sselph/scraper/rom.NewROM(0x11a16440, 0x34, 0x89e71c, 0x0, 0x0)
        C:/Go/projects/src/github.com/sselph/scraper/rom/rom.go:262 +0x130
main.crawlROMs(0x11ba1e80, 0x11ba1d40, 0x4, 0x4, 0x10f58320, 0x10fd9e50, 0x0, 0x0)
        C:/Go/projects/src/github.com/sselph/scraper/scraper.go:333 +0x197a
main.scrape(0x11ba1d40, 0x4, 0x4, 0x10f58320, 0x10fd9e50, 0x0, 0x0)
        C:/Go/projects/src/github.com/sselph/scraper/scraper.go:433 +0x196
main.main()
        C:/Go/projects/src/github.com/sselph/scraper/scraper.go:613 +0xec6

At first I thought it was a bad file, but it seems to end randomly.

I'm running on Windows 7 32bit, with go 1.6.3 32bit.

Let me know if you need any more information

**Comment by sselph** [comment]
Seems to be an issue with it reading a cue file and trying to determine if a bin file exists or not. I'm not handling all the errors possible. I'll fix that.
