### ISSUE TITLE
SNES images not downloading

### ISSUE THREAD

**Issue by necronucleus** [sselph/scraper#107]
I have completely closed out ES and ran your scraper however upon completion, there are no images showing for SNES roms nor is there a directory with downloaded images in /home/pi/emulationstation/downloaded_images.

**Comment by ntelalis** [comment]
I have this exact issue but for every system.

**Comment by sselph** [comment]
I've introduced a bug. I'll have a fix shortly.

**Comment by sselph** [comment]
I renamed the `-gdb_img` flag to `-console_img` but forgot to actually use the new flag so it wasn't downloading images. Sorry about that. The new code is being released now.

**Comment by necronucleus** [comment]
Thank you sir!!! :)
