### ISSUE TITLE
Images not downloading

### ISSUE THREAD

**Issue by alexanderrichards** [sselph/scraper#108]
Hi, new user here so I'm probably doing something wrong. I'm using raspberry pi 3 with retropie 4.X.

I use the built in scraper by dropping to console with F4 then running:

```bash
sudo ~/RetroPie-Setup/retropie_setup.sh
```

then picking `configuration/tools` -> `scraper`.

If I scrape all with thumbs I see the scraper busy doing things. many lines like:

```
INFO: Starting <rom_name>
INFO: Starting <rom_name>
INFO: Starting <rom_name>
```

afterwards I have the `gamelist.xml` file but no `downloaded_images`/`images` directory

Have I made an obvious mistake here somewhere.

----
**Note** my roms are mounted from a network share at the usual place `RetroPie/roms` however this doesn't seem to be an issue for the `gamelist.xml` file creation

**Comment by sselph** [comment]
I fixed a bug last night. Try downloading the latest version.

**Comment by alexanderrichards** [comment]
That seems to have fixed it, thanks very much.
