### ISSUE TITLE
Combine Mamedb and ScreenScraper.fr as a source when scanning for arcade games

### ISSUE THREAD

**Issue by Redemp** [sselph/scraper#113]
Hi i just found out that you added in ScreenScraper.fr in v1.1.10.

There a quite a lot of arcade games documented there so is it possible to use this one with the mame scanning at the same time to get as much result as possible?

**Comment by paradadf** [comment]
mamedb.com is down right now... maybe forever?

**Comment by Redemp** [comment]
:(

**Comment by dankcushions** [comment]
related: @markwkidd has a PR to add good screenshots to the libretro thumbs repo: https://github.com/libretro/libretro-thumbnails/issues/137 - maybe these could be used if accepted.

**Comment by markwkidd** [comment]
Thanks for flagging this @dankcushions 

If there is anything I can do to help make the 'omnibus' MAME thumbnail set useful, please let me know.

(I do like the idea of using filenames to scrape playlists for MAME in order to avoid the issue of nonmerged, split, and merged sets as well as the issue of torrentzip/nontorrentzip.)

**Comment by markwkidd** [comment]
I'm writing to let you all know that the 'omnibus' MAME thumbnail set is now in fact part of the RetroArch thumbnail repo: https://github.com/libretro/libretro-thumbnails/tree/master/MAME

These thumbs were scraped from arcadeitalia, resized to have a maximum width of 512px, and renamed per RetroArch filename convention.

**Comment by markwkidd** [comment]
One more update about libretro/libretro-thumbnails/MAME: the name variations for MAME 0.179 have just been merged into the libretro thumbnail repo. Within the next 24 hours the downloadable MAME thumbnail pack will also update.

**Comment by sselph** [comment]
I added a `-mame_src` flag that will allow you to specify the source order for mame.
