### ISSUE TITLE
Mame db mirror

### ISSUE THREAD

**Issue by PeteLawrence** [sselph/scraper#115]
With Mamedb currently down, and no signs of it returning, I've setup a mirror of the site based on a copy of the site from archive.org.

It can be accessed at [mamedb.blu-ferret.co.uk](http://mamedb.blu-ferret.co.uk)

Many of the listings pages of the site don't work as not all of them have been archived, but from what I've seen the majority of the URL's used by the scraper are present.

This mirror can be used either by resolving mamedb.blu-ferret.co.uk to an IP (it continually changes) and adding entries into /etc/hosts for www.mamedb.com and mamedb.com, or by updating the URL's in mamedb/scraper.go.

**Comment by Redemp** [comment]
@sselph I think this have been missed but there is another Mame/Arcade database that was mentioned over 5 months  ago here

https://retropie.org.uk/forum/topic/1907/scraper-for-mame-and-mess-games

**Comment by trafsta** [comment]
Thanks Pete. using your hosts file redirection method is working great. I spent hours trying to get mame scraping to work, only to discover its not working because mamedb is down permamently! Your archive site works well. Thanks again.

**Comment by bjschneider93** [comment]
Can someone please explain to me how to do this?  I'm very new at this but its driving me nuts that I can't figure out how to scrape my MAME files.  All of my other noms scraped just fine

**Comment by chr0m** [comment]
Lol, just spent ages trying to figure out why MAME scraping wasn't working for me. I'm losing my life to setting up retropie lately ;)

**Comment by jrlepage** [comment]
Also trying to figure out how to do this... I guess if you're going to edit scraper.go you can't use the pre-installed version on RetroPie? Don't exactly understand how to compile from source on RPi.

**Comment by jrlepage** [comment]
Also resolving that mirror into an ip yields multiple results and trying to navigate to any of them directly gives an error...

**Comment by sselph** [comment]
I made this the default @PeteLawrence If this causes too much traffic, let me know and I will shut it off. I want to move to having ScreenScraper be the default for this but it is in the middle of a server migration so not the best timing.

**Comment by jrlepage** [comment]
This is the default when using the -mame flag? Still getting hash not found for 99% of my 0.78 MAME stuff...

**Comment by sselph** [comment]
It is supposed to be the default if you build from source. I haven't
created a new release since my internet is down and will remain that way
until tomorrow.
