### ISSUE TITLE
MAME scraper "unknown image format" when fetching .jpeg extension

### ISSUE THREAD

**Issue by MonkeyWrench32** [sselph/scraper#117]
I set up my hosts file to redirect mamedb.com to mamedb.blu-ferret.co.uk to be able to use the MAME scraper function.

(If anyone wants to know how to do this, add these lines to /etc/hosts on Linux and Mac systems or C:\System32\drivers\etc\hosts on Windows systems.)

`54.230.122.177  mamedb.com`
`54.230.122.177  www.mamedb.com`

Anyway, when it fetches an image with the .jpeg extension I get "unknown image format". This is not a problem with images with the .jpg extension.

Example of problem: http://mamedb.blu-ferret.co.uk/game/arabian/ with the marquee image (http://mamedb.blu-ferret.co.uk/marquees.small/arabian.jpeg).

**Comment by sselph** [comment]
The underlying issue is that the marquee image isn't on the server and is returning a 404. This wasn't an issue on the original site because it didn't display the link if there wasn't an image to back it up. I need to add better recovery when there is an error fetching the image.
