### ISSUE TITLE
missing file csv without hashes

### ISSUE THREAD

**Issue by joeythesaint** [sselph/scraper#118]
I'm not clear what's happening here (though I haven't spent very long looking at the code yet, so maybe it's obvious and I just haven't seen it yet.

When I run any of the recent-ish scrapers on my arcade ROM sets it rarely finds any matches to output to `gameslist.xml`.  I thought I'd go update issue #20 but when I passed the `-missing` option, the CSV file shows up with barely any hashes listed too.  So I went to thegamesdb.com, picked out a handful of games that I could verify were there, dropped the ROMs in their own directory and ran `scraper` on them thus: `scraper -missing file.csv`.  The result is this:

```
Game,Error,Hash,Extra
aliensyn.zip,hash not found,,
galaga.zip,hash not found,d6cb439de0718826d1a0363c9d77de8740b18ecf,
pacman.zip,hash not found,,
rtype.zip,hash not found,60a394ab53afdcbbf9e88083b8dbe8c897170d77,
spyhunt.zip,hash not found,,
```

So I don't really have much to contribute to issue #20 even though, for example, I know `galaga.zip` with the apparent hash `d6cb439de0718826d1a0363c9d77de8740b18ecf` is game ID 7861.

Any idea what's happening here, such that I could contribute a useful list of hashes and game IDs?

**Comment by sselph** [comment]
Sorry, I haven't been active much lately. Like you noticed, the scraper doesn't hash arcade roms correctly. I never attempted to hash these but can pass `-mame` to tell it to look at the file names instead since that is how these are keyed. But I think there is an issue with the data source I'm using for arcade data.
