### ISSUE TITLE
extended ascii character dropped when scraping Pokémon games

### ISSUE THREAD

**Issue by magus424** [sselph/scraper#123]
Example game: http://thegamesdb.net/game/2356

When scraping Game Boy games, including this, it imports as Pokmon instead of Pokémon.

Using latest scraper according to RetroPie's updater option. (on newly installed RetroPie w/latest version as well)

Scraper source: thegamesdb.net
Title setting: thegamesdb

**Comment by sselph** [comment]
I striped them out because they weren't supported in ES but left a flag to disable this behavior. You can do `-strip_unicode=false`

**Comment by magus424** [comment]
But they are supported in ES. If I scrape it from within there, it works correctly.

**Comment by sselph** [comment]
I went ahead and switched the default since they are supported now.
