### ISSUE TITLE
-mame_src flag not working

### ISSUE THREAD

**Issue by jrlepage** [sselph/scraper#125]
I am trying to scrape my arcade roms using the mamedb.com mirror. When I use the -mame flag it appears to be using thegamesdb. I saw in one reply you mentioned adding a -mame_src flag but that doesn't seem to be working either.

Edit: Sorry I misunderstood- that feature is only available in the source not the pre-compiled binaries.

**Comment by sselph** [comment]
Okay, retropie is supposed to be pulling from source but I suspect that it isn't updating when it thinks it is updating. You can try doing the following and reinstalling the scraper.
`sudo rmdir -rf ~/RetroPie-Setup/tmp/build/scraper`

**Comment by jrlepage** [comment]
I just went ahead and compiled from source... my issue now is that when I scrape from screenscraper.fr (which works beautifully otherwise) - it says "unknown" for the name of every game (the rest of the metadata like description, etc. is all fine)...

**Comment by sselph** [comment]
hmm possibly they are actively doing work. Was this mame or console, and do you have an example of a game that did this? My tests have a name populated but maybe there is a particular system or something that is busted.

**Comment by sselph** [comment]
I talked to the Universal XML Scraper developer and he mentioned that some themes aren't working so you could try a different one and see if it helps.

**Comment by jrlepage** [comment]
Thanks I tried the Pixel theme (which doesn't display all of the metadata) and it looks great. May just be happy with that. Carbon was giving issues. Thank you for the help!
