### ISSUE TITLE
[MAME flags] mame_img b=boxart & 3b=3D boxart undocumented

### ISSUE THREAD

**Issue by paradadf** [sselph/scraper#126]
Hi!
When using SS as source **b** and **3b** are valid. GDB allows **b** as well. I'm not sure how you want to handle this.
https://github.com/sselph/scraper/blob/e95edcece65b1d2196f54ad1b0722ad82086df0f/scraper.go#L66

**Comment by sselph** [comment]
Thanks, I can update the documentation. FYI I mapped screen marquee to title since there weren't any title in SS. For GDB I think I mapped boxart to title for neogeo.

**Comment by paradadf** [comment]
Good to know, thanks. SS added flyers for mame not so long ago btw.
