### ISSUE TITLE
Can't disable hash check

### ISSUE THREAD

**Issue by substring** [sselph/scraper#129]
Hi @sselph 

Looks like we can't disable hash check/download. Using `-hash_file` is only valid for TGDB, but OpenVGDB keeps checking if the hash is up to date. Could there be a "more global" option to prevent from checking if the hashes are up-to-date ?

**Comment by sselph** [comment]
I can look in to adding some flags to set these files but it shouldn't be adding a ton of time to the process. Should be on the order of a few hundred milliseconds. Something like this is what the code is doing.

```shell
curl -s -w "%{time_total}\n" -o /dev/null -H 'if-none-match: "bc42a41ec8f627815ea1dee9dfcd9514"' https://storage.googleapis.com/stevenselph.appspot.com/openvgdb2.zip
```

**Comment by substring** [comment]
I remember you were trying to limit switches ... maybe simply add a `-no_hash_check` ?
The reason is that i use your scraper on a per system basis, i don't want it to loose time checking everytime if it has the last hash tables. I run it once with no rom_path so that it updates its hash tables, then full steam out : one system after another.

**Comment by sselph** [comment]
That sounds reasonable. I'll probably call it something like `update_cached_files` or something and setting it to false will disable it. So if there is a copy locally it will not do anything, if it doesn't exist it will download it and this would apply to hash.csv, ovgdb, mamehistory, etc. I've been working on adding my code in to RetroPie/EmulationStation. Now that it is out for testing, I'll probably try and clear out some of these issues tonight.
