### ISSUE TITLE
New SS regions disregarded

### ISSUE THREAD

**Issue by paradadf** [sselph/scraper#132]
I saw you just added "wor", but as there are many more new regions available now, that media isn't being found.
http://www.screenscraper.fr/api/regionsListe.php?devid=xxx&devpassword=yyy&softname=zzz&output=xml&ssid=test&sspassword=test

You still have xx, which I believe isn't valid anymore. Maybe you could change its behaviour to pull out media from any region available if xx is used and no other region before it was available (?). Right now the scraper is getting less media than before :(.
Or read the corresponding region and find if there is media available for the rom's region.

**Comment by sselph** [comment]
The way the XML API is structured and Go's parser doesn't lend itself well to adding new regions. I might be able to use the json API but it is very flaky. I think they are encoding the json themselves instead of using a library so is very error prone.

**Comment by sselph** [comment]
The JSON issues have been corrected. Once the cache on SS has been flushed, I'll see about swapping the code over.

**Comment by paradadf** [comment]
Great news. I don't reslly understand how all that works, but I'm sure the ScreenScraper team is open yo any improvement on the API that you could suggest. Anyway, thank you for looking ito that.

**Comment by paradadf** [comment]
Hi @sselph, I'm not sure what's happening, but I get too many errors now...

Examples:
```
atari2600\Boggle (USA) (Proto).zip,"ss: cannot parse response: ""json: cannot unmarshal object into Go value of type []string""",,
atari2600\Mario Bros. (USA).zip,"ss: cannot parse response(API closed for non-registered members): ""invalid character 'A' looking for beginning of value""",,
atari2600\Radar (USA).zip,"ss: cannot parse response: ""invalid character 'E' looking for beginning of value""",,

"colecovision\BurgerTime (USA, Europe).zip","ss: cannot parse response: ""json: cannot unmarshal object into Go value of type []string""",,

fba_libretro\1942.zip,"ss: cannot parse response: ""invalid character '}' looking for beginning of value""",,
fba_libretro\1941.zip,"ss: cannot parse response: ""json: cannot unmarshal object into Go value of type []string""",,
fba_libretro\aliensyn.zip,"ss: cannot parse response(API closed for non-registered members): ""invalid character 'A' looking for beginning of value""",,

fds\Akumajou Dracula (Japan) (Rev 1) [b].zip,"ss: cannot parse response: ""json: cannot unmarshal object into Go value of type []string""",,

gamegear\Aerial Assault (World).zip,"ss: cannot parse response: ""json: cannot unmarshal object into Go value of type []string""",,
```
I have also problems with
`-extra_ext=".scummvm,.ipf,.mx1,.mx2,.ws,.wsc,.wad"`
Those extensions were perfectly scrapable in the past.
For pbroom (.wad) I get the gamelist, but no downloaded_images.

I'm getting also "downloaded_images" with 0 kb.

**Comment by sselph** [comment]
All those errors are because the responses from ScreenScraper aren't valid json. I'll take a look at some of them and see what I can do. They are hard to trace down. I'll ask Marble what the possible errors are so I can properly handle them.

**Comment by paradadf** [comment]
Any idea about the extra extensions?
I get stuff like this:
`atarist\5th Gear (Europe).zip,No valid roms found in zip.,,`
And it was working before.

**Comment by sselph** [comment]
So the zip contains one of your extra extensions?

**Comment by paradadf** [comment]
Yes, it does.

**Comment by sselph** [comment]
One of the errors is the API has been changed and genres now has this extra data in it

"genres": {
				"genres_id": ["10"],
				**"genre_10_medias" : {
					"genre_10_media_pictoliste" "https://www.screenscraper.fr/api/mediaGroup.php?devid=sselph&devpassword=ROMHasher20160916&softname=scraper&crc=&md5=&sha1=&groupid=10&media=pictoliste&mediaformat=png",
					"genre_10_media_pictomonochrome" : "https://www.screenscraper.fr/api/mediaGroup.php?devid=sselph&devpassword=ROMHasher20160916&softname=scraper&crc=&md5=&sha1=&groupid=10&media=logo-monochrome&mediaformat=png"
				},**
				"genres_de": ["Action"],
				"genres_en": ["Action"],
				"genres_es": ["Acción"],
				"genres_fr": ["Action"],
				"genres_pt": ["Ação"]
			},

**Comment by paradadf** [comment]
Btw, I couldn't scrape one single gamegear rom.

**Comment by paradadf** [comment]
Hi again!
Three things I noticed in v1.2.2:
1.  When the rom exists but it isn't associated you get:
`fba_libretro/1945kiiio.zip,"ss: cannot parse response: ""invalid character 'E' looking for beginning of value""",,`
[Link to the rom in SS.](https://screenscraper.fr/rominfos.php?romid=316265)
2. When the rom doesn't exist you get:
`fba_libretro/beastfp.zip,hash not found,,`
(which is correct)
3. I get `mtwins.zip,,,missing image` despite of the screenshot being there.
https://screenscraper.fr/gameinfos.php?plateforme=75&gameid=79019
This probably happens with other games, I haven't checked one by one yet.
It could be that some parenthesis is wrong place on the database? Or is it something with the scraper?

**Comment by sselph** [comment]
I can take a closer look tonight but the can not parse error means I cant
parse the JSON being returned from SS. This could be that the response is
malformed or it is an error I don't know about. Marble might be able to
diagnose it before I get to it but I can check tonight.

**Comment by paradadf** [comment]
One more error type I found:
`mastersystem\Baku Baku Animal (Brazil).zip,"Get c49a4753?devid=xxx&devpassword=yyy&maxwidth=400&softname=zzz: unsupported protocol scheme """"",,`
[Link to the game](https://screenscraper.fr/gameinfos.php?plateforme=2&gameid=18467)

**Comment by sselph** [comment]
> fba_libretro/1945kiiio.zip,"ss: cannot parse response:

Thanks I hadn't seem that error before. I've added an entry to detect it.

> I get mtwins.zip,,,missing image 

I get this game when I search for that filename https://screenscraper.fr/gameinfos.php?plateforme=75&gameid=44386 This is one I'm not sure how to fix. I wouldn't think MAME would map two games to the same file name so it might be a data error. If this is common and correct, I may have to see if I can pass a hash then fall back to filename only.

> mastersystem\Baku Baku Animal (Brazil).zip,"Get c49a4753?

Is me poorly handling the "xx" region. The region isn't detected because it doesn't match the rom's region. ie the images are labeled `media_box2d_cus` but the region is listed as `br`. I've fixed my code to exclude the crc and other values so they aren't accidentally picked up. 

> n64/Super Mario 64 (USA).n64,"ss: cannot parse response

This is an error in the JSON  response for one of the images. I notified Marble.

**Comment by sselph** [comment]
Do you have an example of the 0kb image? is it always the same, random, etc? The images are also API calls so maybe I'm not handling those correctly if there is an error. Like if the server gets overloaded it seems to switch to closed to registered users. All the responses are still `200 OK` so I don't know any better and would try and save the image to disk. I'll ask Marble if he can give some HTML codes.

If possible, can you open one of the 0kb images in a text editor and see if it is something like `API closed for non-registered members`?

**Comment by paradadf** [comment]
The 0 kb images happens randomly. They are completely empty inside.

About the double entry for arcade roms, this is because game entries were in fact double and they started "erasing" the duplicates from MAME (considered the parent) and creating/copying/filling the entries in, e.g., NeoGeo (cosidered the child).  SS still needs to work on CPSI, CPS II, CPS III, Cave, etc. and clean it up. Is this correct @Universal-Rom-Tools?

About the `""invalid character '.' after object key:value pair""`, is that something that needs to be corrected for every single game that gives that error, so it would be useful if I gather the info?

**Comment by sselph** [comment]
> is that something that needs to be corrected for every single game that gives that error

I notified Marble so hopefully they can track it down from the API call used. It looks like some php variable is being printed instead of being resolved. The region of the image was jp1 so maybe something with that has an issue.

**Comment by paradadf** [comment]
It appears that the 0 kb images is an issue from the server side.

It would be awesome if you could handle the output for the "not associated rom" error, which currently return:
`"ss: cannot parse response: ""invalid character 'E' looking for beginning of value""",,`

**Comment by sselph** [comment]
Hmm I thought I added code to handle that error. Oops I have a typo. I'll also try and mitigate the 0Kb image issue but yeah Screech and I have asked if we can get some more explicit errors to be able to catch these.
