### ISSUE TITLE
It appears that thegamesdb.net isn't up

### ISSUE THREAD

**Issue by tonylambiris** [sselph/scraper#134]
```2017/01/31 17:11:31 arcade  srcs: mamedb,gdb
2017/01/31 17:11:31 console srcs: gdb
2017/01/31 17:11:31 INFO: Checking for new hash.csv.
2017/01/31 17:11:32 INFO: hash.csv "4d0e7c79149a9f3b60a6871ea7869f79" up to date.
It appears that thegamesdb.net isn't up. If you are sure it is use -skip_check to bypass this error.```

Are there any alternative websites this utility supports?

**Comment by sselph** [comment]
scraper -h
-console_src: Comma separated order to prefer console sources,
ss=screenscraper, ovgdb=OpenVGDB, gdb=theGamesDB

The default is -console_src="gdb", you can try "ss" which is a great source.

**Comment by substring** [comment]
looks like TGDB not being up just stops the scraper. See http://pastebin.com/NqP8KwLi
Command line : `scraper -no_thumb=true -max_width=375 -hash_file=/recalbox/share/system/.sselph-scraper/hash.csv -rom_dir=/recalbox/share/roms/lynx -output_file=/recalbox/share/roms/lynx/gamelist.xml -workers=4 -console_src=ss,gdb -mame_src=ss,gdb -console_img=s,b,f,a,l,3b -lang=fr -img_workers=1 -image_path=./downloaded_images -image_dir=/recalbox/share/roms/lynx/downloaded_images`

If tgdb is not the default scraper, it shouldn't halt, should it ?

**Comment by sselph** [comment]
Good point. I recently changed it so it wasn't the first thing. I should
warn and remove it from the list if it is down.

**Comment by HerbFargus** [comment]
I ran it last night and when it didn't pull the images cause gamesdb was down it mangled the gamelist XML (eg left an unfinished tag that looked like `<gamelist/`) it resolved itself when I used screenscraper but yeah wasn't sure what caused it

**Comment by tonylambiris** [comment]
I tried using `ss` as an argument, got a few of these errors before just canceling it for now:
```
2017/02/01 00:13:18 INFO: Starting: /home/pi/RetroPie/roms/megadrive/Aerobiz Supersonic (U) [!].gen
2017/02/01 00:13:18 ERR: error processing /home/pi/RetroPie/roms/megadrive/Aerobiz Supersonic (U) [!].gen: ss: cannot parse response: "invalid character '\\r' in string literal"
2017/02/01 00:13:18 INFO: Starting: /home/pi/RetroPie/roms/megadrive/Aerobiz Supersonic (U) [!].gen
2017/02/01 00:13:19 ERR: error processing /home/pi/RetroPie/roms/megadrive/Aerobiz Supersonic (U) [!].gen: ss: cannot parse response: "invalid character '\\r' in string literal"
```

**Comment by sselph** [comment]
Thanks for the report. I'll relay it to the developer. He is actively
developing so may have created a bug. Or implemented a feature I asked for
and I haven't done my part.

**Comment by tonylambiris** [comment]
Thanks for the quick turnaround on this guys, very much appreciated!

**Comment by sselph** [comment]
I looked at the posted issue in SS. It seems like the "family" which is what they call a series, etc. Has an erroneous newline `\r` in it. I don't know enough or if I'm allowed to correct it. I notified the developer or maybe one of the dev's that watch issues here might see it and correct it.

**Comment by Universal-Rom-Tools** [comment]
Hi sselph, can you tell me where exactly is this new "\r" ?
(In the Json or the XML ?)

In the Json, I don't see this : 
},
			"familles": {
				"familles_id": ["3060"],
				"familles_fr": ["Sonic the Hedgehog"]
			},

Normally marble don't work anymore on the API directly ;)
So I don't know why there is a modification.
(Don't hesitate to pass on the IRC ;) )

**Comment by Universal-Rom-Tools** [comment]
Just see with the boss,

It's not a "new" bug in the API, it's just the the "Aerobiz" familly who have a problem in the DB (the one who submit this familly add a \r at the end (we don't see that at the validation.) It's corrected for this one, but it's not impossible it won't happen again :S (if you can add a check on this on your side it will be great ;) )
