### ISSUE TITLE
Strip scraper before shipping

### ISSUE THREAD

**Issue by tonylambiris** [sselph/scraper#137]
Not necessarily an "issue" but you get a decent amount of file size savings by stripping the binary before shipping:
```
pi@retropie:~ $ ls -lah scraper
-rwxr-xr-x 1 pi pi 9.3M Feb  2 23:06 scraper
pi@retropie:~ $ strip scraper
pi@retropie:~ $ ls -lah scraper
-rwxr-xr-x 1 pi pi 6.2M Feb  4 19:29 scraper
```

I think passing `-w` to go build will accomplish the same thing.

Thanks!

**Comment by sselph** [comment]
Thanks for the tip. I'll look in to it and see. I was worried I may loose the information in a panic but that doesn't seem to be case only when using gdb. I'll look at pprof. I may just remove that from the build entirely and add it in when people have issues.

The flags seem to be `-ldflags="-s -w"` one or both seem strip debugging info documented here https://golang.org/cmd/link/

**Comment by tonylambiris** [comment]
@sselph yeah it's really only needed in resolving debug symbols when using say the `bt` command in gdb.

**Comment by tonylambiris** [comment]
FWIW I've been running a stripped scraper consistently every week without any issues.

**Comment by sselph** [comment]
I updated my release script.
