### ISSUE TITLE
Uninstall Scraper

### ISSUE THREAD

**Issue by symbios24** [sselph/scraper#139]
Hello there great tool one question if i want to uninstall it how can i do it from command line?

Thank you.

**Comment by sselph** [comment]
You remove the scraper binary something like
`rm scraper` or wherever you placed it
Then there is also a cache kept which can be removed using
`rm -rf ~/.sselph-scraper`

on windows the path of the cache is something like this but I don't know the command to delete a directory in windows.
`%HOMEPATH%\Application Data\sselph-scraper`

**Comment by symbios24** [comment]
Hello, thanks for the response i installed the scraper to a raspberry PI through the retropie setup menu so i dont really know where is placed is there a way to remove it with this command --purge remove "name"
or through the retropie setup menu?

**Comment by sselph** [comment]
I don't know if there is an uninstall in there menu but they place the
binary here

`/opt/retropie/supplementary/scraper/scraper`

So you could remove that for our the folder along with the cache I
mentioned. They also compile from source which means they installed the
package `golang` so you could remove it then also run apt-get autoremove

**Comment by symbios24** [comment]
Thanks for the answer, maybe you can add a remove option in an updated version of the tool, like all the emulators have the remove/uninstall feature directly from the retropie menu.

I Scraped many systems with your tool but unfortunately in some systems it cannot find images at all can you add them/add support for them in the scraper in a future release ?

The systems that cannot find images are: Commodore64/Amstrad Cpc/Amiga/AtariST/
Zx Spectrum/Atari800/AppleII/MSX/Zmachine/TI-994A/TRS-80/Tandy/Dragon32

Thank you

**Comment by sselph** [comment]
I'll look in to the remove option in retropie. Also I can probably greatly expand the list of files covered when using ScreenScraper since it has the checksum values built in to the database. You could do this today with something like `-console_src="ss" -extra_ext=".c64,.amiga"` basically just pass the extensions used by the emulator and tell it to use ss as the source. It will send the hash to SS and if there is something there it will work.

**Comment by symbios24** [comment]
thanks for the answer where exactly i write the command -console_src="ss" -extra_ext=".c64,.amiga"
to the command line like this?
and please add support in a future release also for wonderswan and wonderswan color

Thank you
