### ISSUE TITLE
Add flag to specify windows or *nix target

### ISSUE THREAD

**Issue by sselph** [sselph/scraper#14]
The gamelists are currently built assuming that the gamelist will always be on a *nix system so all file paths use / but there should be an option to switch that since emulation station can run on windows.

**Comment by bubble-joe** [comment]
I haven't had any issue building and running scraper on Windows.

**Comment by sselph** [comment]
Are you running EmulationStation on Windows? I was concerned about where the gamelist was going to be read. My use case has always been to copy the gamelist to a linux machine that is running EmulationStation(RetroPie) but it is possible for people to use Windows to run ES.

**Comment by bubble-joe** [comment]
Yes, I am running ES on both Linux and Windows.
The windows version apparently has no problem finding the generated gamelists.

**Comment by sselph** [comment]
Thanks for testing that out! Guess ES is smart enough to figure that out. I'll go ahead and close this bug.
