### ISSUE TITLE
Flyers won't download from ADB

### ISSUE THREAD

**Issue by paradadf** [sselph/scraper#140]
-mame_src="adb"
-mame_img="fly"
Tried using those but not a single image was downloaded.

**Comment by sselph** [comment]
The API doesn't return a flyer url but if I manually set the value it works. I'll ask the dev.

**Comment by paradadf** [comment]
Maybe this helps you out:
https://github.com/pdrb/mamescraper/blob/master/mamescraper/mamescraper.py#L343

**Comment by sselph** [comment]
The dev at ADB added the flyer but I haven't had time to update my script. I hopefully will be able to tonight or tomorrow.

**Comment by paradadf** [comment]
Thanks for the heads up!
