### ISSUE TITLE
Screen Scraper restricting access

### ISSUE THREAD

**Issue by lavadrop** [sselph/scraper#142]
I'm getting this error when using screenscraper:

"api closed for non registered members"

**Comment by sselph** [comment]
This happens when the server gets overloaded. If you don't want this error
you'll have to register and pass the flags for the SS user and password.

**Comment by sselph** [comment]
The parameters are `-ss_user="lavadrop"` and `-ss_password="password"`

**Comment by lavadrop** [comment]
Thank you for the info

**Comment by lacusumok** [comment]
Where/how do I input this I’m sorry I’m a bit of a noob and this seems to only be happening when I scrape megadrive Roms in the B letter section it always happens in the same spot ? all other systems scrape correctly

**Comment by nsantalu** [comment]
Steven, first I'd like to say THANKS! Your scrapper rules.

Any chance you could add an "option" to enter in credentials from the GUI so it passes our screen scrapper creds to the site every time we run it so we don't have to run it from the terminal window?

**Comment by papinist** [comment]
I have added those parameters to \\retropie\configs\all\scraper.cfg
and it seems to work (no more access error)

**Comment by FrightRisk** [comment]
Can you give an example? S. Selph says to put -ss_user etc. in a comand line. But when I look inside scraper.cfg, it is a run-on sentence:

use_thumbs = "0"max_width = "400"max_height = "400"... and so on. Odd. Spaces seem important after 
the tag and after the equals sign, but there is no space between a parameter and the next tag. The help says put a hyphen in front of the parameters "-ss_user", but the .cfg file doesn't seem to use them. So do I want this:

use_thumbs = "0"max_width = "400"ss_user = "myusername"ss_password = "mypassword" 

Also, there is confusion about what account you need to log into. Is this my login for GitHub or for ScreenScraper.fr? 

And lastly, is there a log printed somewhere of what failed? All those lines that were scrolling up my linux command window disappear when scraping is finished and it goes back to the scraper menu.

**Comment by MarbleMad06** [comment]
Please remove all nickname and password screenscraper account before 24h or i'm sandbox the sself developer account

**Comment by sselph** [comment]
What is the specific issue? You don't any users to be able to pass their
credentials to screenscraper?
