### ISSUE TITLE
Add mix image support

### ISSUE THREAD

**Issue by paradadf** [sselph/scraper#144]
I saw your mix-experiment a while back and just wanted to open this as a tracker.
It would be really cool to be able to scrape mix images with your scraper.

**Comment by sselph** [comment]
I added some support. If you tell it to use `mix3` or `mix4` it will do something, if the source is set to `ss`. It only does this for console. It isn't perfect but it is something. If you provide a `max_width` that is large it would probably cause it to look weird.

**Comment by paradadf** [comment]
great news! I did a quick test and it seems to be working nicely!

**Comment by sselph** [comment]
Going to go ahead and mark this done and if there are issues feel free to reopen this or a new issue.
