### ISSUE TITLE
7z support

### ISSUE THREAD

**Issue by avuton** [sselph/scraper#145]
Now that RetroArch has first class support for 7zip, it would be great to see support for it in this scraper.

**Comment by dhry** [comment]
Seconded. All 7z files are being skipped with hash not found. Please incorporate 7z support.

**Comment by sselph** [comment]
I agree.  @arcane47 had created a fork that did this and I was hoping they'd send a PR but I can take a similar approach. There isn't a pure Go 7z library last I checked. So the approach was to look for the locally installed 7z program then, if available, then use it to access the files stored inside.

**Comment by stevetb** [comment]
Agreed, 7Z support would be a great addition.

**Comment by sselph** [comment]
I added 7z support. I did some testing but don't have anything in 7z so the testing was very basic. I tested on windows and had to add some custom logic to update the path to pick it up. Let me know if this does or doesn't work.
