### ISSUE TITLE
Add support for .tgx, .sgx and .gen extensions

### ISSUE THREAD

**Issue by OBurgerGuy** [sselph/scraper#147]
would love if you could add support for .tgx (turbo grafx-16), .sgx (super grafx) and .gen (sega genesis) extensions to the scraper.

**Comment by OBurgerGuy** [comment]
Nix the .gen extension, got that to work; but the .tgx and .sgx aren't recognizing as valid extensions.

**Comment by stevetb** [comment]
For your roms I would suggest only using the No-Intro set.  I am not sure what set your roms are coming from.  In the No-Intro set, Genesis is .md and TurboGrafx is .pce.  I am unsure what SuperGrafx is in the No-Intro set.  

Scraper supports both .md and .pce as file extensions.

**Comment by stevetb** [comment]
@sselph = I am having a bit of trouble with the SuperGrafx titles.  They resolve to a name, but it is not the official No-Intro names.

Example:  The title "Daimakai Mura (Japan).pce" is scraped to a title name of "Ghouls & Ghosts".  There are 5 titles but they all scrape to a different name than the No-Intro name all other titles use.

Here is a list of all of the correct names from No-Intro:
1.   1941 - Counter Attack (Japan)
2.   Aldynes - The Mission Code for Rage Crisis (Japan)
3.   Battle Ace (Japan)
4.   Daimakai Mura (Japan)
5.   Madou King Granzort (Japan)

**Comment by OBurgerGuy** [comment]
I'm using the any set that good tools processes, they're just pce (sgx/tgx) and smd (gen) renamed, gen works for your scraper, all you need is to add the other two, they make sense and as much sense as anything, good tools supports them, please do so as well, thank you



- Vince Forillo

**Comment by OBurgerGuy** [comment]
Also it may help to refer to cowerings good tools: http://cowering.blogspot.com

goodPCE is your target, run them thru that..



- Vince Forillo

**Comment by OBurgerGuy** [comment]
I would just like to clarify that the roms are the same ROMs that you have I just changed the extension to .SGX and .TGX the file format is the same

**Comment by sselph** [comment]
Since `.pce` doesn't require and special processing, you can use this flag to have it process them `-extra_ext=".sgx,.tgx"`

**Comment by OBurgerGuy** [comment]
How do I put the flag and for retropie to do it itself under the scraper in retro pie set up I have no desire of doing this stuff via  command line at the prompt



- Vince Forillo
