### ISSUE TITLE
Have scraper scan .tgx and .sgx automatically

### ISSUE THREAD

**Issue by OBurgerGuy** [sselph/scraper#148]
Would like the scraper to do -extra_ext=".sgx,.tgx" itself, as having it be s manual user command is extremely not helpful

**Comment by sselph** [comment]
.sgx seems like something Mednafen supports but .tgx doens't appear anywhere in the source code.  Is this an official file extension?

**Comment by OBurgerGuy** [comment]
Not official, unless you consider GoodTools official, then yes they're official scene extensions, it's something that was suggested to cowering and he implemented it, it's just an extension change, no file data is altered, they're both just abbreviations it sets them apart from PCE because they're not PCEngine roms they're turbografx-16 and supergrafx roms... it helps organize and differentiate the sets
