### ISSUE TITLE
Cannot scrape roms in USB drive

### ISSUE THREAD

**Issue by felleg** [sselph/scraper#151]
Hi!
I'm having issues scraping roms that are stored on a USB drive. In particular, these are PSX roms. What I did is create a symbolic link in ~/RetroPie/roms/psx to /media/usb/psx_roms

No metadata or image is being downloaded for these roms. Is this normal?

**Comment by sselph** [comment]
There is nothing in the scraper that would prevent it from reading from
wherever you point it. There isn't enough information to tell you what is
happening but I suspect that you don't have bin/cue's that match the ReDump
data. When it is running, do you see a bunch of "hash not found" for each
file and takes a long time? or do you see nothing and it exits very
quickly? The first would be that the roms aren't in my list, the second is
you have .iso or some other file format that isn't supported.

**Comment by felleg** [comment]
Hi sselph, thanks for taking the time to respond quickly! I was able to test it more just now. The first thing I notice (probably unrelated to the scraper but might provide a hint) is that when I boot EmulationStation, it prints messages like this one on the console (the messages are only visible after quitting ES):

lvl0:  File path ""/home/pi/RetroPie/roms/psx/USB_Stick/Twisted Metal.cue"" is outside system path "/home/pi/RetroPie/roms/psx"
lvl0: Error finding/creating FileData for ""/home/pi/RetroPie/roms/psx/USB_Stick/Twisted Metal.cue"", skipping.

Since the USB_Stick folder is my symbolic link to /media/usb/RetroPie/roms, I guess that's why it's seen as outside the system path. As for the actual message that I get when I scrape the roms: There is none. It's as if my directory is completely empty. Does that mean the scraper does not go through the symbolic link?

**Comment by sselph** [comment]
That is it. The scraper doesn't follow symbolic links. So if
RetroPie/roms/psx were a symlink to the folder with roms it should work.
This is also causing ES to complain too. It follows the link, gets the real
path, then complains because it is outside of the path RetroPie/roms/psx.
