### ISSUE TITLE
 BUG 2D images not detected 

### ISSUE THREAD

**Issue by micropixel70** [sselph/scraper#152]
Scraping the 2d images for Mame only finds those of the neo geo, the others are no longer detected why?

Thank you! :-)

**Comment by sselph** [comment]
Hi @micropixel70 I'm going to need a little more information. Do you have the command you are trying to run? Will help be understand the sources that are being used, etc.

**Comment by sselph** [comment]
Looking at the UXS issue, it seems like you got this resolved.
