### ISSUE TITLE
Mame clone of

### ISSUE THREAD

**Issue by cirolaferrara** [sselph/scraper#159]
Please add cloneof tag

**Comment by sselph** [comment]
Do you have any documentation on what is expected for this flag or how it will be used?

**Comment by cirolaferrara** [comment]
Thanks @sselph for reply.

Attract mode (a graphical frontend for command line emulators) uses the fileds: 

_#Name;Title;Emulator;CloneOf;Year;Manufacturer;Category;Players;Rotation;Control;Status;DisplayCount;DisplayType;AltRomname;AltTitle;Extra;Buttons_

gamelist.xml generated from your script gives a lot of the above info but not _CloneOf_ tag.

With it we can convert from gamelist.xml to attract-mode gamelist.

Attract Mode uses _CloneOf_ tag for filtering roms, so if your script can include this tag, the conversion script can be more accurate.

Thank you
