### ISSUE TITLE
[Mix images] Maintain screenshots aspect ratio 

### ISSUE THREAD

**Issue by paradadf** [sselph/scraper#160]
Hi!
When composing the mix images, the aspect ratio of the screenshots should be respected. The images of certain systems with vertical layout get too distorted (e.g. Vectrex).
Example:
![armor attack world -image](https://user-images.githubusercontent.com/15956550/27226127-7c0d63f8-526b-11e7-95f0-91997f398281.png)
It should look like this:
![armor attack world -image](https://user-images.githubusercontent.com/15956550/27226405-df021e4e-526c-11e7-91a4-2c8f4ef795d9.png)

**Comment by sselph** [comment]
Thanks. I'll take a look next chance I get but it might be a couple days.

**Comment by adabo** [comment]
What program are you using to "mix" the two images together? I want to do that for my arcade collection. I like seeing the title and the screenshot at the same time.

But not just arcade. I want to do it with other systems not yet supported by scraper. Just need to know how you're mixing them.

Maybe it's your own code?

**Comment by sselph** [comment]
Sorry I have been busy and haven't had a chance to work on the project. I am using my own code based on the configs from UXS. You could use imagemagick to resize the images then merge them together. I think this is how UXS does it or has at least proposed to do it.

**Comment by paradadf** [comment]
Hi sselph! Would you mind compiling your scraper again after this change so it is accesible for everyone easily? :)
And thanks for fixing this!

**Comment by sselph** [comment]
I forgot to respond but I did release a new binary

**Comment by sselph** [comment]
I'll release another one now that I have fixed the mix4

**Comment by paradadf** [comment]
Thank you!
