### ISSUE TITLE
When scraping video/marquee, specify the name of the console in the filename.

### ISSUE THREAD

**Issue by felleg** [sselph/scraper#163]
Note: This issue might only happen because I set the scraper to download my videos in a folder of my choosing, instead of choosing the default option. I still believe it should be addressed. The reason I set a folder manually is to put it on my USB drive, the SD card has no space for all these videos.

I recently scraped my rom collection to get videos and marquees, and stumbled upon an issue. I'll use Battletoads as an example. This game is on the gamegear, gameboy, genesis and nes. They all share the same name: "Battletoads (U) [!] ._console_". When the scraper finds the video, it becomes "Battletoads (U) [!]-video.mp4", and removes the console from the name.  This creates a conflict between the different versions of a game that shares the same name. Only the first scraped game will have the correct video: indeed, my gameboy, genesis and nes versions play the video from the gamegear version, since it's the earliest in the console listing (gameboy is `gb`).

This issue would be fixed if the console name was included in the name of the video.

**Comment by paradadf** [comment]
Why don't you save the videos in different folders dependion on the platform being scraped instead of all in one single? I don't think adding the console name is a good idea... it just make the filenames longer.

**Comment by felleg** [comment]
I agree, this would solve the issue, and in fact I initially thought this is something the scraper would do automatically, but it didn't, hence my initial comment. If it's my fault for using the wrong flags, simply let me know what I did wrong, and I will gladly close this issue :)

I scraped all of my games at once using the -scrape_all flag. I also used the -nested_img_dir flag, thinking it would do exactly what your comment suggested. I obviously used the -download_videos flag to download the videos, and since I wanted them to be saved on my USB key instead of my SD card, I used the -video_path flag to save it in /media/usb/scraped-videos/.

I assumed that the -nested_img_dir would have split the videos into console directories in my /media/usb/scraped-videos folder, but this is not what happened. They were all put directly into the same folder. Assuming I used the scraper incorrectly, what would have been the correct way to do it?

**Comment by paradadf** [comment]
For an easy way to achieve that, I'd suggest you to use this:
https://github.com/paradadf/recaltools/tree/master/fastscraper
You'll need to change
`-video_dir="%%i\%videoPath:~15,-1%"` (on the batch)
`-video_dir="$i/${videoPath:14}` (on the bash)
to use whichever location you'd like, similarly for the marquee. That'd be adding an absolute path before the `%%i` or `$i`, as that variable becomes the different platform names.

**Comment by felleg** [comment]
Ah, sad that there's no clean way to do it in sselph's scraper itself. I'll have to check out your script. Thanks for sharing.

**Comment by sselph** [comment]
When I get a change, I'll see about adding in the system name when an
absolute path is given in a -scrape_all situation.

**Comment by felleg** [comment]
Thank you!

**Comment by sselph** [comment]
Oops meant to say add in a system folder when there is an absolute path
something like if you do -scrape_all -video_dir /usb/videos then nes should
scrape to /usb/videos/nes

**Comment by felleg** [comment]
Fine with me!
