### ISSUE TITLE
Missing flags?

### ISSUE THREAD

**Issue by InkyPi** [sselph/scraper#164]
Hi, I don't seem to have all the flags that are listed in the wiki. I have my roms stored on usb0 so I run scraper from command line and there is no flag for -use_gdb or -use_ovgdb. I have tried removing scraper and installing again from source but no luck.

**Comment by sselph** [comment]
Looks like the wiki is out of date you can get an up to date list with scraper -h. I merged the flags in to `-console_src` which accepts an ordered list of sources so you can give the order you want the sources searched so you can do something like `-console_src="gdb,ss,ovgdb"`

**Comment by InkyPi** [comment]
Brilliant, thanks!

**Comment by sselph** [comment]
Updated the wiki
