### ISSUE TITLE
PSX-PS1

### ISSUE THREAD

**Issue by symbios24** [sselph/scraper#165]
Hello there. scraper is not working with psx-ps1 games anymore it was working in the past but now it does not find any images/pictures for ps1 pbp files

And also it does not work with computer systems yet eg: amiga/atarist/amstrad/zxspectrum/c64/apple2 etc.

Can you fix that?

Thanks

**Comment by sselph** [comment]
Yeah It only works with bin/cue files. You can try using screenscraper with extra extensions like `-console_src="ss" -extra_ext=".pbp"` This passes the sha1 to screenscraper and hopes they have it in their database. It probably won't work since I think they have less sha1 data for larger files.

**Comment by symbios24** [comment]
Thanks for your help but i dont really know how to run the scrapper manual from the command line, maybe on the next release you can add support for pbp files if its possible.
another strange thing is if i scrape any games from any system from inside emulation station it almost finds any image , is emulation station using a different image source?
