### ISSUE TITLE
Investigate low GB hit rate.

### ISSUE THREAD

**Issue by sselph** [sselph/scraper#17]
A user has reported a low GB hit rate. Double check that dataset.

**Comment by robertybob** [comment]
Hiya, I've scraped again and it's found 195 out of 541. Lots of messages about not finding hashs

![example screenshot](http://i.imgur.com/ImqBadr.png)

**Comment by robertybob** [comment]
Having tried to scrape the first 10 games within Emulationstation itself on Windows, it still can't find certain games - despite me naming them exactly the same as what is on thegamesdb website. This leads me to believe it's a problem with their website, rather than your scraper.

**Comment by sselph** [comment]
Okay a couple things are going on. A couple of the games I'm seeing are in my list so odd that they aren't picked up. Some are more recent additions to the DB so I'll work on adding those to my mapping. But before that I'll create a small tool so you can print out a list of what is missing with some other metadata so I can get a good idea of what is going on. I'll try and get that tool done tonight and maybe tomorrow work to include add the late additions from the gamesdb.

**Comment by sselph** [comment]
I created a prototype for a reporting tool. You run the reporter just like you would the scraper. It will run over all the roms like normal but will looks for missing hashes or known hashes that are missing GDB id in my hash.csv. It will place all the info in a missing.csv and upload info to my server. The screenshot is windows above so I linked the 2 windows versions.
https://storage.googleapis.com/stevenselph.appspot.com/reporter_windows_amd64.zip
https://storage.googleapis.com/stevenselph.appspot.com/reporter_windows_386.zip

**Comment by biscuits99** [comment]
Here are my results
http://speedy.sh/fSvsN/missing.zip

**Comment by sselph** [comment]
Thanks, @biscuits99 Looks like 264 of the GB are actually missing from GDB or I don't have them in my database. I'll go through and check those again. Most of the others don't seem to be the standard releases but I'll check them more closely later tonight.

**Comment by robertybob** [comment]
My results: https://dl.dropboxusercontent.com/u/48342677/missing%20gameboy.csv

**Comment by sselph** [comment]
Thanks for the reports. I went through the GB section and updated it. There are about twice as many ROMs in the list now so that should help. I'll take a closer look at the ROMs where the hash isn't recognized at all and see what I can do.

With my scraper the files name doesn't affect anything as long as it has the correct extension. You should be able to name them a.gb, b.gb and it should be able to figure out which game is which.

**Comment by robertybob** [comment]
Hi Steve,
I've still got 154 GB games where the hash cannot be found - would it be helpful for you if I was to go through and find thegamedb ID number for all of them, for when the hashes are sorted at your end?

**Comment by sselph** [comment]
Sure, I can add your hashes into my dataset. The hash not found means that the hash wasn't in no intros hash set. This could mean they don't have a hash of the rom or that your version of the rom is slightly different. Just 1 bit different causes it not to match.

**Comment by robertybob** [comment]
https://dl.dropboxusercontent.com/u/48342677/GameBoy%20GBD%20IDs%20for%20Hashes%20Not%20Found.csv

149 GB games - had to add 4 to thegamesdb . It's a shame that one bit could cause it not to match, I imagine I'm not the only one who has these exact .rom files. Ah well, if you're able to add them to your database then at least this won't be repeated in the future :)

**Comment by sselph** [comment]
Thanks, those hashes have been added to the collection.

**Comment by robertybob** [comment]
Hi, hope you're doing well. Just to let you know where I am- scraped my GBC games and out of the 240something that were missing, most were because the hash couldn't be found. I've gone through them and found the corresponding thegamesdb ID - about 35 are missing from thegamesdb website itself, so I've got those to add. 

Out of interest, what is there to add/tidy up before you reach beta v1 or a 'stable' release?

**Comment by sselph** [comment]
Thanks again! Just send me the csv when you finish and I'll add those in.

I haven't been thinking about the versions just slowly incrementing the number. Only things I can think of are updating a gamelist instead of always creating a new one to refresh or append to it. Also some code clean up and documentation.

**Comment by robertybob** [comment]
Yeah I was gonna say, I've never come across any bugs or crashes so I wouldn't have a Beta tag anymore :) 

Here's my GBC list with 229 TGDB IDs https://db.tt/AiWGOyMb

**Comment by robertybob** [comment]
Heya, just edited the link in my previous post - I realised I uploaded the wrong spreadsheet (had full URLs instead of just IDs).

**Comment by sselph** [comment]
Thanks. I've added those to the list. Sorry for the delay, I was traveling.

**Comment by robertybob** [comment]
Hi @sselph , I've rescraped my GBC games and 8 of them are incorrectly linked to the same GDB ID

<game id="21931" source="theGamesDB.net">
          <path>./Donkey Kong Country.gbc</path>
          <name>X-Men: Mutant Academy</name>
          <desc></desc>
          <image>./images/Donkey Kong Country-image.jpg</image>
          <thumbnail>./images/Donkey Kong Country-thumb.jpg</thumbnail>
          <releasedate>20000701T000000</releasedate>
          <developer>Crawfish Interactive</developer>
          <publisher>Activision</publisher>
          <genre>Action</genre>
      </game>

<game id="21931" source="theGamesDB.net">
          <path>./Cubix - Robots For Everyone - Race &#39;N Robots.gbc</path>
          <name>X-Men: Mutant Academy</name>
          <desc></desc>
          <image>./images/Cubix - Robots For Everyone - Race &#39;N Robots-image.jpg</image>
          <thumbnail>./images/Cubix - Robots For Everyone - Race &#39;N Robots-thumb.jpg</thumbnail>
          <releasedate>20000701T000000</releasedate>
          <developer>Crawfish Interactive</developer>
          <publisher>Activision</publisher>
          <genre>Action</genre>
      </game>

<game id="21931" source="theGamesDB.net">
          <path>./Dracula - Crazy Vampire.gbc</path>
          <name>X-Men: Mutant Academy</name>
          <desc></desc>
          <image>./images/Dracula - Crazy Vampire-image.jpg</image>
          <thumbnail>./images/Dracula - Crazy Vampire-thumb.jpg</thumbnail>
          <releasedate>20000701T000000</releasedate>
          <developer>Crawfish Interactive</developer>
          <publisher>Activision</publisher>
          <genre>Action</genre>
      </game>

 <game id="21931" source="theGamesDB.net">
          <path>./Emperor&#39;s New Groove, The.gbc</path>
          <name>X-Men: Mutant Academy</name>
          <desc></desc>
          <image>./images/Emperor&#39;s New Groove, The-image.jpg</image>
          <thumbnail>./images/Emperor&#39;s New Groove, The-thumb.jpg</thumbnail>
          <releasedate>20000701T000000</releasedate>
          <developer>Crawfish Interactive</developer>
          <publisher>Activision</publisher>
          <genre>Action</genre>
      </game>

  <game id="21931" source="theGamesDB.net">
          <path>./Quest RPG - Brian&#39;s Journey.gbc</path>
          <name>X-Men: Mutant Academy</name>
          <desc></desc>
          <image>./images/Quest RPG - Brian&#39;s Journey-image.jpg</image>
          <thumbnail>./images/Quest RPG - Brian&#39;s Journey-thumb.jpg</thumbnail>
          <releasedate>20000701T000000</releasedate>
          <developer>Crawfish Interactive</developer>
          <publisher>Activision</publisher>
          <genre>Action</genre>
      </game>

   <game id="21931" source="theGamesDB.net">
          <path>./Rampage 2 - Universal Tour.gbc</path>
          <name>X-Men: Mutant Academy</name>
          <desc></desc>
          <image>./images/Rampage 2 - Universal Tour-image.jpg</image>
          <thumbnail>./images/Rampage 2 - Universal Tour-thumb.jpg</thumbnail>
          <releasedate>20000701T000000</releasedate>
          <developer>Crawfish Interactive</developer>
          <publisher>Activision</publisher>
          <genre>Action</genre>
      </game>

   <game id="21931" source="theGamesDB.net">
          <path>./Robopon - Sun Version.gbc</path>
          <name>X-Men: Mutant Academy</name>
          <desc></desc>
          <image>./images/Robopon - Sun Version-image.jpg</image>
          <thumbnail>./images/Robopon - Sun Version-thumb.jpg</thumbnail>
          <releasedate>20000701T000000</releasedate>
          <developer>Crawfish Interactive</developer>
          <publisher>Activision</publisher>
          <genre>Action</genre>
      </game>

      <game id="21931" source="theGamesDB.net">
          <path>./Rugrats Movie, The.gbc</path>
          <name>X-Men: Mutant Academy</name>
          <desc></desc>
          <image>./images/Rugrats Movie, The-image.jpg</image>
          <thumbnail>./images/Rugrats Movie, The-thumb.jpg</thumbnail>
          <releasedate>20000701T000000</releasedate>
          <developer>Crawfish Interactive</developer>
          <publisher>Activision</publisher>
          <genre>Action</genre>
      </game>

**Comment by sselph** [comment]
The csv you sent has all these having the same hash and that hash happens to be the hash you get when hashing an empty file. I'll remove them from the DB for now. Can you check the size of the original files to ensure they aren't 0 and if they aren't you can run shasum <file> to get me the real values.

**Comment by robertybob** [comment]
I'm really sorry about that, you're 100% correct. I've just checked the files and they are indeed 0kb. Just goes to show I haven't gotten around to playing those yet (!). 

Is there a similar piece of software that runs on Windows? I've Googled shasum and it appears to be Linux only (?)

**Comment by robertybob** [comment]
Hiya. I've got replacement files and they all have hashes associated with them. Feel free to close this issue btw :)
