### ISSUE TITLE
screenscraper.fr cartridge labels

### ISSUE THREAD

**Issue by ruckage** [sselph/scraper#170]
Hello,

First, thank you for your work on the sselph scraper, it's an incredibly useful tool.

I develop themes for retropie and for a theme project I'm currently working on I would like to be able to scrape the cartridge labels for Super Nintendo games that are hosted on screenscraper.fr (on the website they are listed under Supports: label texture).  Is there any way to scrape these images using your scraper tool?

Thanks in advance for any help you can offer.

**Comment by sselph** [comment]
I added `-console_img` options of `cart` and `clabel` for the cartridge and the cartridge label.
