### ISSUE TITLE
Arcade video snaps not showing up (but scrape fine)

### ISSUE THREAD

**Issue by kiaengima27** [sselph/scraper#171]
Hi.

Just set-up a Pi3 and retropie and found your amazing scraper. most systems scrape video snaps fine but i am having trouble with Arcade/mame

All roms are in the arcade folder and most of the titles seems to scrape fine (i can see snaps and videos in the created folder) but when i view the roms in the emaulation station menu the video snaps dont play. snaps seem to work if there is one.

i noticed the rom zip files and video files are named differently.. i have tried renaming the video files but still doesnt work. what the best way of scraping arcade titles and what settings to use?

**Comment by sselph** [comment]
I haven't used any of the video stuff but something like this should work `-mame -mame_src="adb" -download_videos"` You could alternatively substitute `"ss"` for `"adb"` I imagine that adb has better coverage but if the console videos work you might want ss since that is the same source.

Since you are playing on the Pi you could also download handbrakecli and either place it in the same directory as the scraper, in the system path, or if you have already installed the regular handbrake on windows it is already there. Then use `-convert_videos` which will hopefully convert the files to something that will play more easily on the pi. But if you are doing that it is best to probably do that on another system.

**Comment by kiaengima27** [comment]
Thanks Stephen. i sorted it.. used the same scraper as consoles and it works fine now

**Comment by phatazz** [comment]
Hello Kiaengima27,

is there any way you can provide more information on how the problem was fixed, i am having the same issue and i am not sure what you mean by, 'used the same scraper as consoles'.

Thank you!

**Comment by pgbconfirmit** [comment]
@phatazz What this means is, when you're in the Scraper Config/Options page, you set "Arcade Source" to the same value as "Console Source". For me, this meant changing from ArcadeItalia to ScreenScraper.
For what it's worth, my MAME games scraped videos fine from ArcadeItalia, but the videos don't work with the OMX video player. When I turned that off, the videos appeared fine. But I want to use the hardware accelerated player, so I'm going to scrape again with ScreenScraper as the Arcade Source. But I may need to delete the existing videos, as they won't get overwritten I expect (different encoding, so maybe different file extension)

**Comment by FrightRisk** [comment]
Yes, you can scrap from a different source, or re-encode the progetoemma videos from arcadeitalia. I just used Handbrake to batch re-encode all of the scraped snaps to the "normal" or "High Profile" preset and turning down quality to 25 to make the files a little smaller (on par with the original sizes). They play just fine then in OMX.

**Comment by motoschifo** [comment]
The ADB video source could be changed to improve compatibility issues.
Can you make a test with mp4 videos created for Hyperspin, available on the bottom of this page?
http://www.progettosnaps.net/videosnaps

**Comment by motoschifo** [comment]
I have uploaded video samples for 33 games, you can all the files here:
[shortplay native resolution (82MB)](http://adb.arcadeitalia.net/media/test/shortplay.yuv420.zip)
[shortplay scaled to 1080p (314MB)](http://adb.arcadeitalia.net/media/test/shortplay_hd.yuv420.zip)

Please let me know if this solved the compatibility issue, so I will upload all new videos on my web-site for the scraper.

**Comment by smedvedev12** [comment]
> Yes, you can scrap from a different source, or re-encode the progetoemma videos from arcadeitalia. I just used Handbrake to batch re-encode all of the scraped snaps to the "normal" or "High Profile" preset and turning down quality to 25 to make the files a little smaller (on par with the original sizes). They play just fine then in OMX.

Hello.  I'm not a coder, so a lot of this is another language. Any chance you can do a step by step on how to do this? Specifically, how to re-encode in the raspberry pi terminal? Or whichever way is easiest.
