### ISSUE TITLE
Cannot scrape FBA games

### ISSUE THREAD

**Issue by wonx** [sselph/scraper#172]
Hello,

I updated the scraper to the latest version (v1.4.4) using the binaries provided for the raspberry pi 2. I tried it on other systems and seems to work fine, but when I try to scrape the FBA roms directory (with _scraper -mame_, since they are arcade games), I get the following error message after each game:

`ILM Bad HTML`

I tried searching this error message, but I couldn't find anything relevant.

**Comment by sselph** [comment]
This error comes from my code complaining that the response it received wasn't the correct format. I can take a look but you could also switch to another source with something like `-mame_src="adb"` or `-mame_src="ss"`
