### ISSUE TITLE
Permission denied during scraping

### ISSUE THREAD

**Issue by acidrs03** [sselph/scraper#174]
Latest Retropie 4.2 install
Scraper installed from optional packages in retropie-setup
From the pi command line running the scraper configuration and choosing scrape all or scrape chosen systems i get permission denied errors
my output example
2017/08/14 06:53:10 ERR: error processing /home/pi/RetroPie/roms/psx/Einhander (USA).cue: open /home/pi/RetroPie/roms/psx/images/Einhander (USA)-image.jpg: permission denied

Roms are located on a NAS system which could be the cause of the permissions issues. 

Running /home/pi/RetroPie-Setup/retropie-setup.sh as sudo or under sudo su makes no difference.

**Comment by sselph** [comment]
The error is from not being able to write the file to disk. So I would
check the permissions on the folder /home/pi/RetroPie/roms/psx/images.

**Comment by acidrs03** [comment]
Ok for the life of me i cannot change the permissions of the folders on m,y FreeNas to be able to overcome the Permission Denied message.
From withiin RetroPie command line i can mkdir on the freeNas but changing permissions results in Operation not permitted etc. 
I have even gone into the FreeNas web gui and created a user pi and group pi and set it as the owner and owner group of the own retropie Dataset with no luck.

Another Option i was thinking, would be to deselect the use rom folder to store images and gamelist and let it save them to the default location.
This would remove the permission denied i am getting.
Once all the data has been downloaded, could i them just move the images and gamelist files to their respective roms folders.
If so, what file stores the path information for loading the image data. As i would have to edit this file to look for the images in the roms folder.

**Comment by Halvhjearne** [comment]
i have the same problem and none of my other devices connected to this share has any permission problems, however i noticed that when i run the scraper from cli with sudo, it works.
so my guess is its something to do with the user, used to scrape.

**Comment by sselph** [comment]
I haven't tried this on my FreeNAS but there isn't a really anything my code can do. Like @Halvhjearne mentioned it could be the way the /etc/fstab is written and the default isn't allowing non-root write access.

**Comment by c-swinford** [comment]
I had this same issue,but found out that the optional scraper does not input password(most likely). I changed my share to mount as guest and bingo it works.
