### ISSUE TITLE
Steam support

### ISSUE THREAD

**Issue by erikh** [sselph/scraper#177]
I'm going to fork and patch this in so I can get behavior like https://scottrice.github.com/Ice. Would you be willing to accept the changes upstream? I was already working on something like this when I came across your scraper. Looks awesome!

I already have the shortcut bits for steam @ https://github.com/erikh/go-steam-shortcut -- I think I can just drop this in after crawlROMs and get pretty far. I just don't have a lot of time to maintain a large project like this, but i'm happy to keep the steam support working if you let me know when I'm needed.

Thanks!

**Comment by erikh** [comment]
https://github.com/sselph/scraper/compare/master...erikh:steam?expand=1 watch this patch if you're interested.

already:

<img width="1858" alt="screen shot 2017-08-27 at 7 10 13 am" src="https://user-images.githubusercontent.com/18923/29750637-4aa5a6f2-8af8-11e7-96d1-7aaa66dab2da.png">

**Comment by sselph** [comment]
Cool. Yeah lately I haven't had a ton of time to main things but if you add a feature I'm happy to mention your name if there are issues with your feature I can't fix.

**Comment by erikh** [comment]
All good. I'll see what progress I can make this weekend and will report
back. Thanks!

**Comment by erikh** [comment]
decided to take a different route here, so I figured I'd close this to spare your tracker.

The library to generate / manage steam shortcuts in go is here: https://github.com/erikh/go-steam-shortcut. Please feel free (or reach out if you're paranoid) if anyone wants to continue this work, happy to get anyone kickstarted.
