### ISSUE TITLE
GBA Video Snaps Skipping Majority of Games

### ISSUE THREAD

**Issue by Mitshiba** [sselph/scraper#178]
Hiya:

I wasn't sure if there was an issue with where I'm scrapping, or just that particular system. All the other systems I've scrapped came out perfect and this is the only one I've had an issue with. Wasn't sure if it was a bug, place of scraping, or just doing something wrong with the Retropie.

I read in forums to delete the gamelist.xml and re-scan which worked for all the other systems I had issues with except this one. After scrapping is complete and I restart the system, all the images art comes up but only about 3 or 4 of the games scrapped have video and the rest do not. Has anyone else ran into this issue or have had something similar or know how to fix this?

Thank you,
Mitshiba

**Comment by sselph** [comment]
I'm at work and can't look in depth but it may be that the system in
screenscraper is lacking videos.
https://screenscraper.fr/gamesinfos.php?plateforme=12&numpage=0

Everything there is done by a small community so they may not have gotten
to that system or found a source of videos. Check a few games there and see
if that is the case. If it isn't then maybe it is something else.

**Comment by Mitshiba** [comment]
Cool beans, thanks for the quick response 👍 I see there missing a bunch of video snaps of the games I have, but there are a few snaps in the list that they have but didn't scrape which could be anything...

I'll register an account with them and see if I can make some video snaps to upload to their servers of some missing games and see if that fixes the issues I'm having :)

**Comment by sselph** [comment]
I can't really think of a reason why only one system wouldn't so hopefully that is it.

**Comment by Mitshiba** [comment]
I've uploaded a bunch of video clips to their server. That seems to be the issue :). Had a couple of games that had wrong links but is now fixed. 3 out of the 17 videos I've uploaded so far have been approved and more to come.

**Comment by sselph** [comment]
Awesome and thanks for contributing!
