### ISSUE TITLE
thegamesdb.net broke the scraper connection

### ISSUE THREAD

**Issue by CharfatoS** [sselph/scraper#179]
Hi, after one day and a half thegamesdb.net went offline, today i just cant run scraper successfully... Tried over romsets that worked before without any issue, but now just throw error... With -skip_check go with no errors but scraper can't validate hash for any rom (Like if the hash was missing, but the hash.csv still there).

**Comment by raelgc** [comment]
Is there a way to use other source than thegamesdb.net?

**Comment by sselph** [comment]
-console_src="ss" you can see the documentation with -h but the flag
accepts an ordered list of sources to try.

**Comment by raelgc** [comment]
@sselph Oh man, I quickly took a look yesterday, before go to bed, and missed that option (never play with computers while sleepy). Really sorry to disturb you with something that is documented.

@CharfatoS: just run `scraper -console_src="ss"` (options to use are ss=screenscraper, ovgdb=OpenVGDB, gdb=theGamesDB).

And please, close this issue :smile:

**Comment by CharfatoS** [comment]
Oh my gosh i missed that too, i thought `-use_nointro=true` or `-use_ovgdb=true` or`-use_gdb=false` do that same thing, but missed that sorry :( ... Still, i think the source thegamesdb.net (Default source) broke things, maybe they update their feeds or idk... Thanks this works successfully :D

**Comment by sselph** [comment]
Not a problem. My power has been out since Monday so only have a spotty
phone connection, but when it comes back I'll take a closer look. A while
back I changed the -use_ flags to the single flag so you could also give
the order.
