### ISSUE TITLE
ss: API closed for non-registered members

### ISSUE THREAD

**Issue by retrop** [sselph/scraper#184]
Trying to scrape and I get the above error. i am also getting errors saying TLS handshake timeout, so I am really confused on what to do to continue scraping.

**Comment by gugueU** [comment]
I 've got the same issue as you.
I found the solution here
https://github.com/sselph/scraper/issues/142

I launch the script manually like this from the rom directory

sudo /opt/retropie/supplementary/scraper/./scraper -append -console_src ss -ss_user="lavadrop" -ss_password="password" -download_videos -download_images -hash_file "/opt/retropie/supplementary/scraper/myhash.csv" -lang="fr,en,jp"

**Comment by MerhuBerahu** [comment]
Also Getting this, not on every rom though, but quite a lot.

**Comment by AdmiralP** [comment]
My guess would be here that anyone using this should update the command respectively with their own access information:

`-ss_user="lavadrop" -ss_password="password"`

becomes

`-ss_user="yourgithubusername" -ss_password="yourgithubpassword"`

Note that Steven's response was to a user named lavadrop, and that is probably why you see the command listed as "-ss_user="lavadrop" in the answer.

**Comment by gugueU** [comment]
I created my own ScreenScraper account, and it works

**Comment by sselph** [comment]
Sorry for the delay. So when screenscraper.fr gets overloaded it starts restricting itself to registered users only so you will have to create an account and give the screenscraper.fr credentials via the `-ss_user` and `-ss_password` flags.

I think if the servers are REALLY overloaded it can even restrict further to users that have uploaded content.

**Comment by FrightRisk** [comment]
@AdmiralP said this:

 -ss_user="yourgithubusername" -ss_password="yourgithubpassword"

This is incorrect, is it not? You need your screenscraper.fr password, NOT the github password, right? As in:
--_user="your screenscraper.fr password" -ss_password="screenscraper.fr password"

**Comment by gumpy123** [comment]
I'm a little late for this one but I am now getting this same message, I'm running this script but it's taking forever just to login?
sudo /opt/retropie/supplementary/scraper/./scraper -append -console_src ss -ss_user="I used my username" -ss_password="I used my password" -download_videos -download_images -hash_file "/opt/retropie/supplementary/scraper/hash.csv" -lang="fr,en,jp"

**Comment by WolfgangLaRocco** [comment]
I, too, am also getting the message
"arcade srcs:
console srcs: ss
open /opt/retropie/supplementary/scraper/myhash.csv: no such file or directory"

**Comment by AdmiralP** [comment]
> @AdmiralP said this:
> 
> -ss_user="yourgithubusername" -ss_password="yourgithubpassword"
> 
> This is incorrect, is it not? You need your screenscraper.fr password, NOT the github password, right? As in:
> --_user="your screenscraper.fr password" -ss_password="screenscraper.fr password"

Sorry for the late reply, but you are correct. I misspoke and the screenscraper creds are what are/were needed.

**Comment by WolfgangLaRocco** [comment]
I've followed everything in this thread and even have my own SS username and password, and I still get the same API Closed error. There isn't a single step I skipped or method mention I haven;t tried. What am I doing wrong? Where do I even log my info in?

**Comment by AdmiralP** [comment]
> I've followed everything in this thread and even have my own SS username and password, and I still get the same API Closed error. There isn't a single step I skipped or method mention I haven;t tried. What am I doing wrong? Where do I even log my info in?

According to the link listed above (issue [#142](https://github.com/sselph/scraper/issues/142)) you would edit the scraper config file. You can edit the file with nano by typing:

sudo nano /opt/retropie/configs/scraper.cfg

The final file should look something like this: 
`use_thumbs = "1"
max_width = "400"
max_height = "400"
console_src = "2"
mame_src = "2"
rom_name = "0"
append_only = 0"
use_rom_folder = "1"
download_videos = "1"
download_marquees = "1"
-ss_user = "your username"
-ss_password = "your password"`

**Comment by WolfgangLaRocco** [comment]
I had to actually create the file from scratch because it didn't exist. Even with entering all the information and my login/password from screenscraper.fr, I still get the "API closed" error. I really don't understand.

**Comment by AdmiralP** [comment]
Ultimately, there is no guarantee it will work either way. As Steven said above, 

> I think if the servers are REALLY overloaded it can even restrict further to users that have uploaded content.

EDIT while typing... because I see your edit... good to hear. My guess is you will have better luck if you try again another time. Chances are the servers are just getting hit pretty hard.

**Comment by ksimir** [comment]
This video explains how to edit the scraper script to add the username and password for ScreenScraper. I tested, it works.

https://www.youtube.com/watch?v=N2YxbLXJNWk

**Comment by AdmiralP** [comment]
> This video explains how to edit the scraper script to add the username and password for ScreenScraper. I tested, it works.
> 
> https://www.youtube.com/watch?v=N2YxbLXJNWk

Thanks for this Samir - the vid quality is not the greatest (that's not your fault), but the content is accurate and should help a lot of people here.

Side note: the creator of the video stated that there could be issues registering if you translate the page. For what it is worth, I translated it and had zero issues. So at the very least it would not hurt to try it. If it fails you can always reload the page and try it sans translation.

**Comment by WolfgangLaRocco** [comment]
> This video explains how to edit the scraper script to add the username and password for ScreenScraper. I tested, it works.
> 
> https://www.youtube.com/watch?v=N2YxbLXJNWk

This video is EXACTLY what I needed to get this going finally! Thank you so much!!

**Comment by Biff-Libation** [comment]
Thank you for pointing out that video ksimir! Worked perfectly.

**Comment by MarbleMad06** [comment]
Please remove all nickname and password screenscraper account before 24h or i'm sandbox the sself developer account

**Comment by MarbleMad06** [comment]
in all issue comment

**Comment by AdmiralP** [comment]
> Please remove all nickname and password screenscraper account before 24h or i'm sandbox the sself developer account

I am not sure I follow. What is your intention here?

**Comment by MarbleMad06** [comment]
I'm MarbleMad, creator and super administrator (god) of screenscraper ! the user & password indicate in this issue and anover issue is used by lot of people and directly added to the IP sandbox !

**Comment by sselph** [comment]
I'm still unsure what you are asking about Marble. You mean the "your
username" and "your password" as a placeholder for someone to put in their
actual name and password? What would you think is a suitable example to
use? These aren't obviously real credentials.

>

**Comment by sselph** [comment]
This is the equivalent of --ss_user="votre nom" --ss_password="votre mot de
passe"

>

**Comment by J-Swift** [comment]
It looks like he wants you to delete the github comments that show the username and passwords because people are not understanding not to actually use those values on the consumer side

**Comment by MarbleMad06** [comment]
and the username and password used for the example is an existing and sandboxed account

**Comment by AdmiralP** [comment]
I believe I have updated my replies in such a manner as to keep it's relevance, but remove the actual username. Please let me know if this is sufficient @MarbleMad06.

**Comment by MarbleMad06** [comment]
perfect thanks
