### ISSUE TITLE
Low GG Hit rate

### ISSUE THREAD

**Issue by robertybob** [sselph/scraper#19]
Hi Sselph, 
I've scraped 258 GameGear games and hashs for only 101 games have been found. is this down to my roms or a databse thing like the GB low hit rate potentially is?

**Comment by robertybob** [comment]
Just realised thegamesdb only have circa 150 games listed on their site. When I find the time this week I'll begin to add the ones I have that are missing from their website.

**Comment by robertybob** [comment]
Hi @sselph , have added 141 GG games to thegames.db website - I think this is now 99% of all EU and NA games. Do you need to do anything at your end or will your scraper now find everything?

**Comment by sselph** [comment]
Nice! I need to get them mapped over to the hashes. I'll get that done this weekend. And I haven't forgotten the script that reports missing information, I've almost finished it.

**Comment by sselph** [comment]
Thanks for all the hard work. I added all the new GG games to the mappings it ended up being ~170 games.

**Comment by robertybob** [comment]
That's great to hear, although I imagine coding is more hard work  (!).  Do you mean you found 170 new games, or there are 170 in total?

**Comment by sselph** [comment]
170 new roms for 353 total. Some could be clones so the number of games could be slightly less.

**Comment by robertybob** [comment]
Just scraped again, only 20 something missing, so this is no longer an issue for me.
