### ISSUE TITLE
Constant scrape crash on few specific games with -download_marquees="true"

### ISSUE THREAD

**Issue by IceLancerSR** [sselph/scraper#190]
Hey there.
I am getting constant tool crash on few specific mame games.
columns.zip is one of them
command -download_marquees="true"

2017/11/08 00:10:18 arcade srcs:
2017/11/08 00:10:18 console srcs: ss,gdb,ovgdb
2017/11/08 00:10:18 INFO: Checking for new hash.csv.
2017/11/08 00:10:19 INFO: hash.csv "d9eedf6e622a8ab6a1a14486bb90ffb8" up to date.
2017/11/08 00:10:20 INFO: Checking for new OpenVGDB.
2017/11/08 00:10:20 INFO: Upgrading OpenGDB: -> "bc42a41ec8f627815ea1dee9dfcd9514".
2017/11/08 00:10:22 INFO: Upgrade Complete.
2017/11/08 00:10:22 INFO: Starting: test\columns.zip
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x709c45]

goroutine 65 [running]:
github.com/sselph/scraper/rom.getImage(0x9470c0, 0xc042047d80, 0x0, 0x0, 0xc04293a1e0, 0x16, 0x190, 0x0, 0x0, 0x0)
/home/sselph/go/src/github.com/sselph/scraper/rom/rom.go:366 +0xf5
github.com/sselph/scraper/rom.(*ROM).XML(0xc042e2ba80, 0x9470c0, 0xc042047d80, 0xc042049400, 0x6, 0x8, 0xc04203fb10)
/home/sselph/go/src/github.com/sselph/scraper/rom/rom.go:495 +0x62d
main.worker(0x9470c0, 0xc042047d80, 0xc042940180, 0x6, 0x8, 0xc042049400, 0xc04203fb10, 0xc04301a480, 0xc04301a4e0, 0xc042280a80)
/home/sselph/go/src/github.com/sselph/scraper/scraper.go:140 +0x4e8
created by main.crawlROMs
/home/sselph/go/src/github.com/sselph/scraper/scraper.go:223 +0x66b

Start : 0:10:18.64
Finish : 0:10:23.40
---------------
Duration : 00:00:04,76

Win10 x64

**Comment by IceLancerSR** [comment]
Fresh compiled from Git. Its still crashing 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x709c45]

goroutine 11 [running]:
github.com/sselph/scraper/rom.getImage(0x9470c0, 0xc042045dc0, 0x0, 0x0, 0xc0444afae0, 0x19, 0x190, 0x0, 0x0, 0x0)
        /home/sselph/go/src/github.com/sselph/scraper/rom/rom.go:366 +0xf5
github.com/sselph/scraper/rom.(*ROM).XML(0xc044424b80, 0x9470c0, 0xc042045dc0, 0xc042047180, 0x4, 0x4, 0xc04203db30)
        /home/sselph/go/src/github.com/sselph/scraper/rom/rom.go:450 +0xc60
main.worker(0x9470c0, 0xc042045dc0, 0xc042650280, 0x4, 0x4, 0xc042047180, 0xc04203db30, 0xc04387a2a0, 0xc04387a660, 0xc0420089e0)
        /home/sselph/go/src/github.com/sselph/scraper/scraper.go:140 +0x4e8
created by main.crawlROMs
        /home/sselph/go/src/github.com/sselph/scraper/scraper.go:223 +0x66b

**Comment by IceLancerSR** [comment]
Thanks, working fine, no crash. tested again with fresh compile

**Comment by sselph** [comment]
Great to hear. I couldn't find exactly why this was happening but added some checks to at least prevent it from crashing the entire program.
