### ISSUE TITLE
PCE Games not scraped with 7z?

### ISSUE THREAD

**Issue by kruuth** [sselph/scraper#192]
I've been trying to scrape PCE roms from the GoodPCE set.  They're combined 7z roms, so "Aero Blasters.7z" has like 6 files, all versions of the rom.  Do I need to just have individual rom files in individual ZIP or 7z files to properly scrape?

**Comment by paradadf** [comment]
Yes, you need individual files. Most likely, you’ll find zip files inside. Very few emulators use 7z files btw. El

**Comment by sselph** [comment]
The scraper will stop when it finds the first file that has a recognized extension so in a goodset this would likely not be the one with a good hash since it includes bad roms. Also my code can't decompress 7z natively so it requires that you have 7zip installed.
