### ISSUE TITLE
Unable to download videos/snaps

### ISSUE THREAD

**Issue by GRAnimated** [sselph/scraper#196]
Alright, first of all I am using it on windows, which it seems is not widely used.

The thing in CMD i am doing is "scraper.exe -download_videos -use_nointro_name", which just downloads the images as if i didn't put the 2 arguments in the command.

If anyone could help, please do!

**Comment by sselph** [comment]
Try `-console_src="ss"` the default source doesn't have any videos or if it does, I haven't added support.

**Comment by GRAnimated** [comment]
That seems to work, thank you. Will it end up doing the game lists at one point? The game lists aren't getting updated at all but it's still downloading the videos.

**Comment by sselph** [comment]
It doesn't write the gamelist incrementally so once it is interrupted or it finishes it will write the file to disk.

**Comment by GRAnimated** [comment]
Thanks for making the scraper and clearing up these issues I had.

**Comment by sselph** [comment]
No Problem, glad I could help.
