### ISSUE TITLE
Arcade video snaps not showing up (but scrape fine) 

### ISSUE THREAD

**Issue by phatazz** [sselph/scraper#202]
Hello,

I recently downloaded video snaps for my Raspberry Pi3 but i am having issues with MAME videos showing up.  All other systems are working perfectly but can't seem to figure out what the problem is.  

In an earlier post  Kiaengima27 used the same scraper as consoles and it works fine now.

Any idea what was done??

Thank you!

**Comment by sselph** [comment]
If you are running this from the command line you'd add `-mame -mame_src="ss"` to use ScreenScraper as the source. If you are using RetroPie there is an option in the menu to change the source for console and arcade so switch them both to ScreenScraper.fr

**Comment by phatazz** [comment]
Thank you so much! 

This worked perfectly!!

Thank you again!
