### ISSUE TITLE
Mame titles not scraping (fix included)

### ISSUE THREAD

**Issue by MongoBongo** [sselph/scraper#21]
Hey sselph.  
I love this program, it makes it so much easier to scrape than via EmualtionStation,  I came across one issue and that was the title screen scraping for mame did not return any results, I have found the culprit in the source and recomplied and it worked perfect after the changes,  
Might be worth considering to make the changes on the main branch. 

In mamedb.go change the following, 
***
##### Line 34, replace:  
`	titleImgRE   = regexp.MustCompile("<img src='/title/(.*?)\\.png'")`  
##### With:  
`	titleImgRE   = regexp.MustCompile("<img src='/titles/(.*?)\\.png'")`
***
Hope this helps someone out :)  
Mongo

**Comment by sselph** [comment]
Thanks. I incorporated the fix into the master branch and will roll out a fix to the binaries.
