### ISSUE TITLE
Refresh / Scan All folders

### ISSUE THREAD

**Issue by Maikeximu** [sselph/scraper#22]
It would be nice to scan all but to achieve this, the users would have to edit a .cfg file or something stating :
* Folders (because of different emulators)
* Creating images folders in each folder

Then the script would automatically fetch the informations based on the current folder the scraper is on.

I don't know if it's doable. 

Thanks for everything !

**Comment by sselph** [comment]
You mean reading something like es_systems.cfg to get all the roms folders and then using that to scan all the rom folders and writing the gamelists and images to the correct folders?

**Comment by Maikeximu** [comment]
Yes something like. One command line and all the data would be updated without `cd` to each system everytime.

**Comment by sselph** [comment]
I added a -scrape_all flag. If you run the script on a system with ES installed it should attempt to scrape every rom folder on the system. It still places then gamelist and images in the rom folder itself.
