### ISSUE TITLE
Megadrive\Genesis EOF issue

### ISSUE THREAD

**Issue by LodanZark** [sselph/scraper#23]
It seems the improvements made to scrape MD\Gen on 6.6 beta update wasn't enough, I still have issues with Megadrive\Genesis EOF error.
Version Tested: 7.2 beta
compression: zip (32kb)
internal extension: *.smd

**Comment by sselph** [comment]
Hi,
My recent changes should've removed any code in my MD handler that could return "unexpected EOF". If you wouldn't mind giving a few more details to help me narrow it down, that would be great.

Are there any other files in the zip, if so what are the extensions of the files?
Does this error occur if you unzip the file?  ```$ unzip rom.zip``` on linux
If it does work unzipped, what happens if you re-zip it? ```$ zip rom2.zip internal.smd```
What is the uncompressed size of the smd?

**Comment by LodanZark** [comment]
I will explain the process I have done maybe there is some clue to fix the issue.
As example I did pick up a rom validated with GoodGen 3.00 called “Contra - Hard Corps (U) [!].smd”  (CRC32: C579F45E), then using the winrar 5.21 I compressed to zip format with 32kb compression ratio which result “Contra - Hard Corps (U) [!].zip” (CRC32: 13457243).
I store the rom into RPi in specific folder “/home/pi/RetroPie/roms/megadrive”, I uncompress it to test it:
$ unzip ‘Contra - Hard Corps (U) [!].zip’
And it worked well:
$ Archieve:  Contra - Hard Corps (U) [!].zip
$       inflating : Contra - Hard Corps (U) [!].smd
I compressed the unzipped file as you asked:
$ zip rom2.zip ‘Contra - Hard Corps (U) [!].smd’
$       adding:  Contra - Hard Corps (U) [!].smd (deflated 80%)

The commands I have used to scrape was:
$ wget https://github.com/sselph/scraper/releases/download/v0.7.2-beta/scraper_rpi.zip
$ touch /tmp/hash.csv
$ cd ~/RetroPie/roms/megadrive
$ scraper -hash_file /tmp/hash.csv -add_not_found -image_suffix=""

It worked well to scrape game gear, nes, master system, game boy color and Gameboy, only Genesis\Mega Drive got the EOF error.

**Comment by LodanZark** [comment]
Oopsy I did a noobish mistake, I've forgot to ovewright  the old version into new version by the command  "$ sudo unzip scraper_rpi.zip scraper -d /usr/local/bin/".
Sorry for taking your time.

**Comment by sselph** [comment]
No problem. Glad you got it working.
