### ISSUE TITLE
Please Add Support To Rename ROM Files

### ISSUE THREAD

**Issue by josephcole** [sselph/scraper#24]
First of all, this is by far the fastest and most accurate scraper I've found! Thank you! I use this to scrape all the thousands of games I have.

However, one feature I would like to see is the ability to rename the ROM files (ie: -rename_romfiles). This is an example shell snippet I use to rename my nes ROMS that can maybe give you an idea:

cd roms/nes
#Create new ROM dir
DESTDIR=../nes.new
mkdir $DESTDIR
#Scrape ROM info skipping images
scraper -download_images=false -use_ovgdb=true
#Iterate through generated gamelist.xml and rename the ROMS
IFS="
"
for LINE in $(grep -e '<path>' -e '<name>' gamelist.xml | sed 's/name>$/name>~/g' | tr -d '\n' | tr '~' '\n' | tr '<' '>')
do
 #Recode xml/html back to ascii
 FILENAME="$(echo "$LINE" | awk -F '>' '{print $3}' | recode html..ascii)"
 GAMENAME="$(echo "$LINE" | awk -F '>' '{print $7}' | recode html..ascii)"
 #Append gametype ROM to file name
 GAMETYPE=""
 file "$FILENAME" | grep Horiz && GAMETYPE=" (Horizontal)"
 file "$FILENAME" | grep Vert && GAMETYPE=" (Vertical)"
 file "$FILENAME" | grep SRAM && GAMETYPE="$GAMETYPE (SRAM)"
 mv -i "$FILENAME" "$DESTDIR/$GAMENAME$GAMETYPE.nes"
done
#Scrape ROMS again with the new filenames
cd $DESTDIR
scraper -use_ovgdb=true

**Comment by sselph** [comment]
I recently wrote a script to rename some roms for a friend. I can see about adding it in as a feature/standalone app. I'll have to do a bit more work on my current script to make it ready for general use like, duplicate destination names, existing save and image information, etc.

**Comment by sselph** [comment]
Sorry for taking so long. I was working on refactoring code so I could reuse the logic for the renaming. I'll see about adding this to the released binaries and add some documentation but it is here:
https://github.com/sselph/scraper/tree/master/rename

and you can run it like:
./rename *.nes
That will just print out what is being renamed
./rename -dry_run=false *.nes
will actually rename things.
