### ISSUE TITLE
Scrape for ingame snapshots?

### ISSUE THREAD

**Issue by geoffyuen** [sselph/scraper#25]
I understand this might not be what this scaper is for but is there a way to get ingame images instead of boxart?

**Comment by robertybob** [comment]
This scraper only scrapes from thegamesdb.net (which doesn't hold in game screenshots) and only then does it scrape the front box-art. 

Your best bet is the emumovies equivalent scraper, the free version of which has certain limitations - if you chose to pay for it then it's fairly reasonably priced.

**Comment by sselph** [comment]
As robertybob said, this is using thegamesdb for the images and the front box art is the most consistently available image. I have added a flag for you to tell it the type of image and have fall back options if the first choice is unavailable.

It works like:
-gdb_img "s,b"
This will try and get the first screenshot then fall back to the box art when not available.
