### ISSUE TITLE
Scrape mame roms with .7z file extension

### ISSUE THREAD

**Issue by calle81** [sselph/scraper#26]
Hi, 
Thank you for this excellent scraper :) I have one problem though:
My Mame rom set is zipped with 7zip and all files have the .7z file extension. When i run the scraper it doesn't find any roms. Have I missed a command line switch or is 7zip currently unsupported?

Kind Regards,
Carl

**Comment by waille** [comment]
Hi,

I have same issue all my mame roms are in .7z format and scraper is not picking up anything.

**Comment by sselph** [comment]
I'm sorry it took so long to get to this. I've been traveling and was busy. I've checked in the code and will push out a version later this evening.

**Comment by waille** [comment]
Thank you. Was just about to convert all my roms. Perfect timing. Excellent scaping tool by the way, used it for all my other roms, very fast and accurate compared to the one included in ES.
