### ISSUE TITLE
Could not successfully install Scraper on RetroPie 4.8

### ISSUE THREAD

**Issue by GuidoBartoli** [sselph/scraper#266]
Hi, I have problems with **Scraper** installation, these are the steps I followed:

1. Fresh install of RetroPie 4.8 on a Raspberry Pi 4B with 4GB RAM and 256 GB MicroSD Card
2. Update of all the Raspberry software with `sudo apt update && sudo apt upgrade && sudo apt autoremove`
3. Standard configuration of RetroPie (Locale, WiFi, Controller, Audio, ...)
4. Add the optional `lr-mame2003-plus` emulator via RetroPie Setup
5. Direct ROMs transfer on the Micro SD for various emulators (MAME, SNES, GBC, PSX, ...)
6. I followed [this guide](https://youtu.be/rj1841sL8ro) to install Scraper

Unfortunately, when I choose ["Install from source"](https://youtu.be/rj1841sL8ro?t=140), this is the output:

```
Log started at: Wed 26 Oct 07:21:00 CEST 2022

RetroPie-Setup version: 4.8 (6e83a7d5)
System: rpi4 (armv7l) - Raspbian GNU/Linux 10 (buster) - Linux retropie 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

= = = = = = = = = = = = = = = = = = = = =
Installing dependencies for 'scraper' : Scraper for EmulationStation by Steven Selph
= = = = = = = = = = = = = = = = = = = = =


= = = = = = = = = = = = = = = = = = = = =
Installing (binary) 'golang' : Golang binary install
= = = = = = = = = = = = = = = = = = = = =

Current Go version: go1.8.7
/home/pi/RetroPie-Setup/tmp/build/scraper /home/pi

= = = = = = = = = = = = = = = = = = = = =
Getting sources for 'scraper' : Scraper for EmulationStation by Steven Selph
= = = = = = = = = = = = = = = = = = = = =

# github.com/J-Swift/thegamesdb-swagger-client-go
src/github.com/J-Swift/thegamesdb-swagger-client-go/client.go:440: dec.DisallowUnknownFields undefined (type *json.Decoder has no field or method DisallowUnknownFields)
/home/pi
/home/pi/RetroPie-Setup/tmp/build/scraper /home/pi

= = = = = = = = = = = = = = = = = = = = =
Building 'scraper' : Scraper for EmulationStation by Steven Selph
= = = = = = = = = = = = = = = = = = = = =

# github.com/J-Swift/thegamesdb-swagger-client-go
src/github.com/J-Swift/thegamesdb-swagger-client-go/client.go:440: dec.DisallowUnknownFields undefined (type *json.Decoder has no field or method DisallowUnknownFields)
/home/pi
/home/pi/RetroPie-Setup/tmp/build/scraper /home/pi
Could not successfully install Scraper for EmulationStation by Steven Selph (/home/pi/RetroPie-Setup/tmp/build/scraper/scraper not found).
/home/pi

Log ended at: Wed 26 Oct 07:21:10 CEST 2022
Total running time: 0 hours, 0 mins, 10 secs
```
This ends with the message "Could not successfully install Scraper" and the installation stops.

Judging from the logs, it seems the error is coming from `thegamesdb-swagger-client-go`, but I have no clue why and how it can be solved.

Does anyone else have this problem? Is there an alternative way (pre-built binary?) to install Scraper? Any suggestion is appreciated!

Thanks

**Comment by pferdinand** [comment]
I had the same issue and I solved it by launching the retropie setup, then select `Update RetroPie-Setup script`.
Once the update completed, the scrapper installation worked.

**Comment by GuidoBartoli** [comment]
> I had the same issue and I solved it by launching the retropie setup, then select `Update RetroPie-Setup script`.
> Once the update completed, the scrapper installation worked.

Ok, that way worked fine, thanks!
