### ISSUE TITLE
Add hash for game

### ISSUE THREAD

**Issue by Pacolo** [sselph/scraper#29]
Hi, I added this game to TGDB: http://thegamesdb.net/search/?string=Super+Soukoban&function=Search but the scraper can't find it.

Of course, the game is in No-Intro set: http://datomatic.no-intro.org/?page=show_record&s=49&n=2865

**Comment by robertybob** [comment]
Seeing as there's an issue already open to update all hashes, would it not be best to add your game/link there? ( [issue 20](https://github.com/sselph/scraper/issues/20) )

If a new issue was opened for every game that's missing from this scraper, poor @sselph would be spending dozens of hours closing down each one individually lol

**Comment by dagavi** [comment]
Done, sorry.

**Comment by Pacolo** [comment]
I added the
