### ISSUE TITLE
Save gamelist.xml on CTRL+C

### ISSUE THREAD

**Issue by neitanod** [sselph/scraper#31]
Sometimes the sraper hangs because a network event never occurs.  It's still stoppable with CTRL+C, but the gamelist.xml does not get generated.
It would be nice to get the partial scraped list into an XML, and a way to resume the process.

**Comment by sselph** [comment]
I tried to implement this. Let me know how it goes. It should stop processing and attempts to cancel inflight http requests then write the gamelist.

**Comment by sselph** [comment]
forgot to mention the -append flag I added will look to see if the output file already exists and if it does reads it and skips any roms that are already listed. That should cover the resuming.

**Comment by neitanod** [comment]
Superb!

The -workers flag make a huge difference also.  It should probably be more
visible in the documentation, don't you think?

--
Sebastián Grignoli

2015-05-19 12:28 GMT-03:00 Steven Selph <notifications@github.com>:
