### ISSUE TITLE
Description missing from FinalBurnAlpha roms

### ISSUE THREAD

**Issue by nickdj** [sselph/scraper#32]
I hope someone can point me in the right direction.

I've been working on a batch process to scrape a roms directory on Windows and output the results in a format which can be easily imported into Recalbox (EmulationStation).  This is working great for most roms, however, with FBA roms I'm getting no description although everything else is there.

Can someone point me in the right direction?  I've tried different options and get the same results.

**Comment by sselph** [comment]
This is because the mame/fba logic is using a different source(mamedb) and the source doesn't have description information. There are other sources of the information but I haven't attempted to pull those in yet.

**Comment by nickdj** [comment]
Thank you for letting me know as I thought it was something I was doing wrong.  The scraper within Recalbox works for the descriptions so will use this in the meantime. :-)

**Comment by sselph** [comment]
NP I based my MAME scraper off of @digitalLumberjack code so I'll see if there are some improvements I can make. Also he created a fork of my script for recalbox that changes a few of the defaults(can mimic with -max_width=375 -no_thumb) and adds in the region and proto/original stuff over at https://github.com/digitalLumberjack/scraper
-max_width=375 -no_thumb to two of the changes that were made but the other 2 requ
