### ISSUE TITLE
Image destination

### ISSUE THREAD

**Issue by Messij** [sselph/scraper#36]
Is there a way to change the downloaded images destination.
I would like them in the same folder than the rom, even if the rom is in a subfolder.
For exemple in my snes folder I have 4 folders: All, Best, Nintendo and RPG with roms inside each folders. I wold like the images corseponding to these game in the same folder as the rom and the gamelist.xml in the snes folder with good paths.
Thank for your work !!

**Comment by sselph** [comment]
if you are running the scraper inside the rom directory something like this might work. Let me know how it goes since I've never tried it.
```bash
$ scraper -image_dir="." -image_path="." -nested_img_dir
```

**Comment by sselph** [comment]
Closing. Feel free to reopen if there are issues.
