### ISSUE TITLE
Problems with go get.

### ISSUE THREAD

**Issue by mkevins** [sselph/scraper#38]
I have go version 1.2.1 linux/amd64 from the 14.04 Ubuntu repositories. This version matches the version in the example at the top of the readme. A few search results on the errors suggested using a newer version of go. Was something changed that broke this for the repo version?

Here are the errors after running ```go get github.com/sselph/scraper```

```text
# github.com/sselph/scraper
.go/src/github.com/sselph/scraper/scraper.go:738: unknown net.Dialer field 'KeepAlive' in struct literal
.go/src/github.com/sselph/scraper/scraper.go:740: unknown http.Transport field 'TLSHandshakeTimeout' in struct literal
```

**Comment by sselph** [comment]
Sorry I moved my version of go to 1.4.2 and didn't test if I was backward compatible. I am thinking of adding some build testing to catch this in the future. I'll investigate if I can implement this same functionality without requiring newer versions of Go.

**Comment by sselph** [comment]
Let me know if that fixes things. I merged in a bunch of changes one which should take care of the build issues in go1.2

**Comment by mkevins** [comment]
That was a fast response! Yes, the fixes seem to have worked. It compiles with stock go from the repos now. I will close the issue. Thanks you!
