### ISSUE TITLE
Use filename for name

### ISSUE THREAD

**Issue by ProxyCell** [sselph/scraper#4]
I would like to have the games named after the file name so that a game named "Cool Game (USA).nes" will be named "Cool Game (USA)" in the xml

Would this be possible for implementation?

**Comment by ProxyCell** [comment]
ok, this worked out wonderfully! i tested it on the gamegear games and all is good :)

**Comment by ProxyCell** [comment]
ok, spoke a bit too soon. i noticed that with games which do not exist in the database are not added to the gamelist.xml at all. i'm sure this was intentional but would it be possible to allow the scraper to add in games to the gamelist.xml with their filename? I just found a game gear game called Baku Baku Animal (USA) and Baku Baku (Europe) which were not found in the hash table, gdb or ovgdb
That game (and others) will still show up as just their default Emulation Station display (two games called Baku Baku Animal)

**Comment by sselph** [comment]
Ah so the default ES display strips out things in parens? and so you want to have an empty entry added with just the file name as a name?

**Comment by ProxyCell** [comment]
i know you could just add it as a new option/argument but again, its up to you and if it is even within the scope of this app. i deeply appreciate the work you have put into this.

**Comment by sselph** [comment]
Added support for No Intro names in the hash.csv and set using them when available as the default.
