### ISSUE TITLE
Unsupported protocol scheme

### ISSUE THREAD

**Issue by biscuits99** [sselph/scraper#41]
Great new mame scraping functionality, but I do get this error on some fba based roms

ERR: error processing theroes.zip: Get : unsupported protocol scheme ""
ERR: error processing woodpeck.zip: Get : unsupported protocol scheme ""
ERR: error processing sraider.zip: Get : unsupported protocol scheme ""

I ran "scraper -mame" on the Raspberry Pi

**Comment by sselph** [comment]
Thanks. I think I found the issue. When a game had no images available I was attempting to get the URL "" instead of skipping the download. I'll see if there are any more issues then roll out a fix tonight.
