### ISSUE TITLE
scraper not reading full directory

### ISSUE THREAD

**Issue by johnnybravo1** [sselph/scraper#42]
Hi,

Thanks for taking the time to write such a useful tool!

I have an issue that I can't figure out... When I run "scraper -thumb_only" (v0.9.3-beta for PI 2) in my roms directory, it only reads one or two entries then ends. I've removed the gamelist and tried again but it still only picks up the same one or two roms, there are many more in the directory. This is for snes and megadrive.

The -mame flag works perfectly :)

**Comment by sselph** [comment]
Can you give me a couple more details?

Does it give not found errors for everything and only adds 1-2 things to the gamelist? or does it only ever mention the 1-2 files?

**Comment by johnnybravo1** [comment]
It only ever mentions the same 1 file for my SNES ROMs, and 2 for megadrive
(one of the ROMs for megadrive is "not found") but the rest appear to be
ignored.

I have no idea why it only sees those files every time, there are many more
with the same file extension.

**Comment by sselph** [comment]
Odd can you email me the listing (ls -lh) or shasum(shasum *) of the files.

**Comment by johnnybravo1** [comment]
Here is the listing:

https://www.dropbox.com/s/2kcs19elyphd0y5/snes_rom_dir.txt?dl=0

I've also ran the scraper and printed out the gamelist.xml at the end of
the file so you can see the output.

Looking at it more closely, only the .smc and .bin extensions are scraped.
Is there anyway to include .zip and .srm?

**Comment by johnnybravo1** [comment]
OK, so unzipping the files works fine :)

Is there a way to scrape .zip? Normally there would be no need to unzip, shame to lose the all that saved disk space!

**Comment by sselph** [comment]
it used to put looks like i introduce a bug. I'll get it fix in the next couple hours.

**Comment by sselph** [comment]
Okay v0.9.4 should hopefully fix the issue.

**Comment by johnnybravo1** [comment]
Just tested v0.9.4 - Now reads all zip files. 

Thank you!

**Comment by sselph** [comment]
Thanks for finding the issue.
