### ISSUE TITLE
Add Neo Geo Pocket support

### ISSUE THREAD

**Issue by Ekstreme** [sselph/scraper#43]
Please add NGP and NGP Color. Thanks.

**Comment by robertybob** [comment]
There's only 7 NGP and 47 NGP Colour games on thegames.db . Were more than released? 
If so, you're best signing up to that website, adding all the missing games, then asking @sselph  so he doesn't have to keep going back and adding individual games periodically.

**Comment by Ekstreme** [comment]
No more release AFAIK. The issues is they are considered separate systems. emuationstation scraper won't look up NGPC

**Comment by stevetb** [comment]
@sselph = If you setup this platform I will generate the hashes and link to TheGamesDB.

**Comment by sselph** [comment]
Support has been added for the extension .ngp. There are no hashes in no-intro so will wait for some hashes.

**Comment by stevetb** [comment]
@sselph I will be out of town for a week.  When I return I will start the process of scraping all the roms & variations of roms I can find.  Redump will be a guide as well to ensure I capture everything.  Thank you again for your help and your excellent scraper!!!!!

**Comment by stevetb** [comment]
@sselph 

Here is the complete No-Intro Romset for Neo Geo Pocket:

https://drive.google.com/open?id=1PVq4BAkwDM_Qet-ErjOt_oQKJn8_ymFvouwY6Csz7PY

**Comment by sselph** [comment]
Added hashes

**Comment by stevetb** [comment]
@sselph This looks 100% from my end.  I think it is safe to say this is Supported now through scraper.

Please close this thread, we did it!  Yay!
