### ISSUE TITLE
Allow -add_not_found to scrape any file extension

### ISSUE THREAD

**Issue by locvez** [sselph/scraper#44]
Hi,

Firstly, amazing tool, thank you for developing it.

Would it be possible to allow the scraper to scrape any file extension when using the -add_not_found switch? I have 4400 Sinclair Spectrum games and I had to use Bulk Rename Utility to rename all the .z80 files to .zip's and back again once scraped.

I was going to do the same with my BBC Micro games but I noticed some of them have different file extensions.

This would make sense seeing as we know these files are not going to be present in TGDB

**Comment by locvez** [comment]
Just an addendum to this - Would it be possible to add a -extensions switch that would allow us to specify custom extensions? 

I just find it useful that it can list all discovered roms, even if they don't have metadata / artwork attached as ES removes all text within parenthesis which is handy to keep if you have multiple roms with the same name but it specifies region, or other specifics (for example (48k) or (128k) in the spectrum roms)

So could we then (if this change was implemented) run scraper with the following command : 
scraper -add_not_found  -extensions .tap .z80 to list all .tap files and all .z80 files in the spectrum rom folder?

Thanks!

**Comment by sselph** [comment]
Hi, I had a similar idea when I first saw the issue I just haven't had much time to work on anything over the past week.

**Comment by locvez** [comment]
Thanks for this! You rock!
