### ISSUE TITLE
Option to specify region (US/EUR) for images?

### ISSUE THREAD

**Issue by Liquidream** [sselph/scraper#45]
Hi,
Is it possible to add an option (or tell me how) I can specify to download the European/UK version of covers (e.g. "blue" Megadrive covers, as opposed to "red" Genesis ones)?
I'd be happy for the scraper to fall-back on "US" cover, if no "EUR" equivalent can be found.
Not sure how many other systems this would apply to?
(Note: If it should be pulling the correct cover from the hash of the rom, I was only scraping "(EUROPE)" versions of megadrive roms)
Many thanks (this is SUCH a better scraper than the EmulationStation native one! :+1: ),
Paul

**Comment by robertybob** [comment]
If you scrape games as Megadrive it'll pull Megadrive images from thegamesdb. The only issue is that people repeatedly upload Genesis covers and getting them replaced can take months and months for a mod to approve it.

**Comment by sselph** [comment]
Thanks. I can do some of this on my side by trying to match the games marked as megadrive in thegamesdb to the non-US hashes and genesis to US hashes and if it isn't available falling back to the other version. As @robertybob mentioned it also has to be correct in thegamesdb. When I make the next pass of Sega/MD I'll keep this in mind. The first pass I did I just grabbed the first match I saw.

**Comment by robertybob** [comment]
Honestly, it's not worth spending any of your time on it @sselph until every Megadrive entry is there and every entry has the correct artwork. 

In the mean time (and I know it could be a rather big job) you'll have to make do with scraping as normal, then hunting down and replacing Genesis images with Megadrive ones. It's not that hard to do, just check out SegaRetro for hundreds of hi-res MG box arts.

**Comment by Liquidream** [comment]
Thanks for the advice guys. :grinning: 
Doing the scraping from the \megadrive folder seems to have improved the accuracy, but understand there's little that can be done if the source is "inconsistent". 
TBH, I may already have the covers downloaded somewhere, so if I can really be fussed, I may do the manual task. Maybe. :wink:

**Comment by stevetb** [comment]
This issue is resolved through MegaDrive vs Genesis through the rom directories within RetroPie.

I suggest we move to close this issue.

-Steve

**Comment by stevetb** [comment]
@sselph Can we close this?

**Comment by sselph** [comment]
I think so
