### ISSUE TITLE
[Suggestion] RetroPie Module

### ISSUE THREAD

**Issue by HerbFargus** [sselph/scraper#46]
Perhaps I should open up this ticket on the retropie github page rather than here, but as your scraper seems to be quite a bit more effective than the built in scraper for emulationstation- Do you think its viable to code your scraper as a retropie setup-script module? Granted it would probably run from the setup script rather than from emulationstation like the other one, but I think it would still work that way.

**Comment by sselph** [comment]
I proposed this several months ago in
https://github.com/RetroPie/RetroPie-Setup/issues/578
But we concluded it would be much better as part of emulation station so I checked in
https://github.com/Aloshi/EmulationStation/pull/355

Since aloshi got a job development has slowed down, so this hasn't made it to the stable branch. I've also been busy but if someone had time I don't mind someone adding in a module to run this. I'm happy to provide advice. 

I wrote a bash based update check for another script here that does something similar to what you probably want
https://github.com/Death259/PiAssist/pull/18

**Comment by HerbFargus** [comment]
Yeah emulationstation development has kinda been at a standstill for a while so I figure it's best to just integrate stuff with retropie while I can as there's no telling when emulationstation will resume development, and if/when it does resume in the future then our changes can be adapted and pushed upstream. Personally I think your scraper should be the default as it runs much faster and is more accurate.

I like what you've done with the piassist script, I've sorta been using that as a base for adapting into  a retropie module. One thing that I'm curious about is the emulationstation processes- I know that you say they should be killed before you do any scraping- but it's hard to script a kill process when it's set up to automatically reboot within 5 seconds anytime the process is killed. Since the RetroPie setup script is in the retropie menu- it would automatically imply emulationstation will be running when a lot of the people run the script- is there a way to automate it so that people don't have to exit all the way out, or will they have to start the setup script from the terminal if they wish to use the scraper?

**Comment by sselph** [comment]
Very nice. I've never had issues and never really did any tests to see if there were issues. If there are issues, I think it might be that ES waits until it is closed to write to disk and it might do that regardless of things being edited inside ES. I think if you trigger the script from ES it might solve that issue.

**Comment by sselph** [comment]
Also, right now -scrape_all doesn't know to change settings when it finds an arcade platform. I'll fix that soon.

**Comment by HerbFargus** [comment]
That will be a very useful change- I'm looking forward to it. Looks like jools will be integrating it into the retropie setup script sometime in the future, so I'll close this issue. Thanks for the input and your work with this scraper :)
