### ISSUE TITLE
GIMME_ARM should be GOARM in .travis.yml

### ISSUE THREAD

**Issue by edvakf** [sselph/scraper#47]
This project: https://github.com/sselph/scraper/blob/master/.travis.yml

```
    - GIMME_OS=linux GIMME_ARCH=arm GIMME_ARM=6
```

Some other project: https://github.com/rackspace/rack/blob/master/.travis.yml

```
  - GIMME_OS=linux GIMME_ARCH=arm GOARM=6
  - GIMME_OS=linux GIMME_ARCH=arm GOARM=7
```

Seems like gimme doesn't check for GIMME_ARM https://github.com/travis-ci/gimme/blob/master/gimme

**Comment by sselph** [comment]
Thanks! I updated the file.
