### ISSUE TITLE
Ignore dot files

### ISSUE THREAD

**Issue by the0neWhoKnocks** [sselph/scraper#48]
I have a folder called `.unused` in my system directories, for example `/roms/snes/.unused`. In that directory are ROMs that I may revisit at a later date. Emulationstation will ignore that directory since it's a dot file, but scraper will dive in and scrape everything in there.

Would it be possible for you to remove that behavior, or is there a flag that would enable me to ignore specified sub-directories? Something like `-ignore_dir .unused`.

**Comment by sselph** [comment]
Thanks. I've added a filter to skip any directory or file that starts with .

**Comment by the0neWhoKnocks** [comment]
Cool, thanks for the quick turn around.

**Comment by the0neWhoKnocks** [comment]
Finally had a chance this weekend to update the script, works like a charm, thanks again.
