### ISSUE TITLE
Emulation Station not loading post-scrape

### ISSUE THREAD

**Issue by gubernatorial** [sselph/scraper#5]
Emulation Station doesn't seem to load after scraping, using v0.5.5-beta rpi.zip for retropie 2.3.  I'm receiving the following: 

emulationstation: /opt/retropie/supplementary/EmulationStation/src/FileData.cpp:102: void FileData::addChild(FileData*): Assertion 'mType == FOLDER' failed.

Any thoughts as to what might be causing this to happen and how I might be able to get this up and running again?  Thanks for your help.﻿

**Comment by sselph** [comment]
You could delete the gamelist.xml file the script created which should get it up again. I think maybe there is something wrong with the gamelist file that is being created that is throwing off ES. I'll try running this on my retropie and reading the ES code, but in the meantime can you provide me with a little more information? Do you have several folders in your rom dir or are all the roms in a single folder? Did you provide any command line arguments to the script?

**Comment by gubernatorial** [comment]
Looks like that was it.  Deleting gamelist got ES back up and running.

I had each rom in a standalone folder, so I placed all roms in
RetroPie/roms/[console] and ran scraper again to create a new gamelist
file.  Works like a charm.

Much thanks for the assist and for all your work on the scraper.

On Fri, Jan 2, 2015 at 12:17 PM, Steven Selph <notifications@github.com>
wrote:

> You could delete the gamelist.xml file the script created which should get
> it up again. I think maybe there is something wrong with the gamelist file
> that is being created that is throwing off ES. I'll try running this on my
> retropie and reading the ES code, but in the meantime can you provide me
> with a little more information? Do you have several folders in your rom dir
> or are all the roms in a single folder? Did you provide any command line
> arguments to the script?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sselph/scraper/issues/5#issuecomment-68543484>.
>



-- 
Joshua Baron Cahn
(516) 524-7308
jbcahn@gmail.com

**Comment by sselph** [comment]
Glad you got it working. I looked more into the issue and ES was trying add a file to a file while parsing the gamelist. Maybe the multiple nested directories was throwing off my script and I wrote some nonsense or ES wasn't sure what to do with that directory structure.
