### ISSUE TITLE
-mame extension not fully compatible with merged sets

### ISSUE THREAD

**Issue by locvez** [sselph/scraper#50]
It appears that the scraper, when operating in mame mode, is not compatible with the "MAME 0.165 ROMs (T7Z-Merged)" set from the Pleasuredome tracker. I get a lot of "rom not found" errors. It previously worked fine with the "MAME 0.164 ROMs (Torrentzipped-split)" but I cleared out my split collection to use the merged collection purely because it saves about 20gb of space.

Is there anything I can do to help resolve this? I thought that the mame function worked off the file names so I am unsure if the names are different between both sets.

**Comment by locvez** [comment]
Need to check with non-merged sets before raising this as an issue I suppose..

**Comment by sselph** [comment]
The mame does have issues right now it just looks at mamedb.com which is at 0.147 so could be that there are several things no in the DB or merging changes the names to something not in the DB.
