### ISSUE TITLE
Sega CD / Mega CD Support

### ISSUE THREAD

**Issue by robertybob** [sselph/scraper#51]
Hey, I've just upgraded to a Pi 2 so am taking advantage of systems which I couldn't play before. 

The hashes for these games are on redump.org so should be straightforward to set up? I'll provide as much assistance as I can :) Shouldn't take too long compared to PSX I imagine (far fewer games!)

I've just noticed that there are some games missing from redump.org however I'll help filling the gaps.

**Comment by sselph** [comment]
Hi @robertybob,

I apologize for not responding sooner. I can set up a shared sheet if you like but yeah should be straightforward if the hashes are in a DB like redump. I'll see if I can't get something together tonight.

**Comment by robertybob** [comment]
Brilliant! Give me a shout when it's set up :)

**Comment by sselph** [comment]
I shared a sheet with you. I think I have most of the things in redump matched but but there are several games in thegamesdb that aren't in redump. Most seem to be video or interactive movie type games. redump is all bin/cue so if you happen to have iso or other formats let me know and we can get the sha1 of them to incorporate.

**Comment by robertybob** [comment]
Brilliant. I have .bin and .cue too. I haven't had a chance to look at it this weekend , so apologies for that. I normally work on this kinda stuff during my lunch break at work , so I'll do so tomorrow :) 

Have you updated the Reporter tool lately? Would you be able to email it to me as I think I left my only copy on a USB stick I recently corrupted.

**Comment by robertybob** [comment]
Right, looked through the list now and know what I need to do. 
Going forward, Thegamesdb.net's forums are back up and running now and I may ask about the possibility of splitting the Sega CD and Mega CD (like they've done so with the Megadrive and Genesis). If this happens, will a new list need to be created?

**Comment by sselph** [comment]
Probably but it wasn't too hard to create to begin with.

**Comment by robertybob** [comment]
Ah ok, I'll let you know if and when that happens :) 
I've updated the spreadsheet as much as I can - can this now be implemented?

**Comment by sselph** [comment]
Thanks, I've updated the hash information. I haven't forgotten that I owe you a better tool for hashing. I haven't updated it since the original so will be good to do that.

**Comment by robertybob** [comment]
I've just run the scraper for the first time and sadly I must have a abnormal rom-set as only 34 hashes out of 154 could be found. 
https://www.dropbox.com/s/3p760ueci6bupom/missing.csv?dl=0

Also, in some cases it created entries in the gamelist.xml for both .bin and .cue of a game. e.g. Flink.bin and Flink.cue. See:
https://www.dropbox.com/s/i195z08x93v8pzz/gamelist.xml?dl=0
Is this supposed to happen?

**Comment by sselph** [comment]
No that isn't supposed to happen. I'll take a look tonight.

**Comment by sselph** [comment]
The bin/cue both being added could happen if the bin file was renamed. If you open the .cue file in a text editor you will notice it is readable and essentially lists the bin files. If you renamed them the cue would no longer point at the bin which is how I how I was linking the 2.

I'll take a look at the missing

**Comment by robertybob** [comment]
@sselph Ah yes you're correct - the .cue files were pointing to .BIN rather than .bin. Let me know when you've updated the hashes :)

**Comment by sselph** [comment]
Added your missing list and also removed 20k duplicate lines from the hash.csv.

**Comment by robertybob** [comment]
Many thanks :) My Pi's power supply has died so I can't test this, but I'll still close this.

**Comment by robertybob** [comment]
I've just scraped again and this time only 37 weren't found (out of 154). 
I ran the reporter and for some reason it's not finding the many hashes for the .bin files at all (yet when these games are scraped the scraper.exe finds the details using the .cue files, so I'm a bit confused).
I'm not sure how best to send you the hashes of the games that weren't scraped, when the hashes generated by the reporter.exe must be wrong (if you say you've added them to the hash.csv) as they're still not being found (?)

**Comment by robertybob** [comment]
Hey. DId my previous post make sense? Let me know if you need clarification :)

**Comment by sselph** [comment]
That reporter is old and I need to make a new copy. You could try the shasum I mentioned in #20 but that would hash all the games not just the ones that are missing.

**Comment by sselph** [comment]
I also just added a feature to pass the -missing flag with a filename and it will write all the missing ROM information to that file. filename, error, hash, and an extra note like missing image, or that the hash is known but there wasn't a GDB ID.

**Comment by robertybob** [comment]
Thanks! I normally scrape on my laptop but I'll attempt this on my Pi soon :)

**Comment by robertybob** [comment]
Hi @sselph sorry for the delay. Ran your scraper from my Pi for the first time ! Used the missing image flag and got the following:
https://www.dropbox.com/s/qp4qmc4wspm4sdh/file?dl=0

Are you able to add these hashes to your database?

**Comment by robertybob** [comment]
@sselph ? :)

**Comment by sselph** [comment]
Sorry most my free time has been spent playing fallout. I'll try to get to these tonight.

**Comment by sselph** [comment]
Added these. Let me know if that works.

**Comment by robertybob** [comment]
Many thanks, I'll have a go at scraping again tonight :)

**Comment by robertybob** [comment]
Because it takes a while to scrape all the games, I've done the first few from that list and they scrape fine, so presuming they all do. Thank you for doing this :)
