### ISSUE TITLE
Add FBA support??

### ISSUE THREAD

**Issue by Haris1977** [sselph/scraper#53]
As the title says :)

**Comment by sselph** [comment]
I think this might work with the -mame flag. I'm ignorant when it comes to those platforms and probably should've used -arcade for the flag name. If it is working, I can update the README and maybe rename the flag.

**Comment by objectchris** [comment]
I can confirm it works with the -mame flag. i think the fba romsets are a subset of mame, so it's probably the same hashes.

**Comment by sselph** [comment]
I updated the README but left the flag name alone for compatibility/simplicity reasons.
