### ISSUE TITLE
Turbografx specific roms error when scrapping

### ISSUE THREAD

**Issue by Haris1977** [sselph/scraper#55]
I got errors (hash not found) when scrapping these games (pcengine-turbografx):

Gradius (J)
Lode Runner - Lost Labyrinth (J)
P-47 - The Freedom Fighter (J)
Shinobi (J)
Soldier Blade Special - Caravan Stage (J)
Violent Soldier (J)
W Ring - The Double Rings (J)

Is there any way to tell the system to scrape specific local images for these roms? Any help?

I use 

cd ~/RetroPie/roms/pcengine
scraper -thumb_only

**Comment by Haris1977** [comment]
Well, I used the retropie in-game scrapper to scrape those 7 files with success:)

**Comment by sselph** [comment]
Hi. Sorry for the delayed response. You can use -add_not_found to have it add them to the gamelist file with no information and it will add an image if there is one already there with the name it expects. Or you can do like you did and use the builtin scraper with the option to only scrape things without images.
