### ISSUE TITLE
Add option to output file with skipped(missing) roms -no data and or missing image

### ISSUE THREAD

**Issue by israelperez** [sselph/scraper#56]
Thanks for all your efforts sselph 
I was wondering if you could add this so that its easier to manage roms that where skipped or that have missing images.

that way a user can manually edit the meta data

**Comment by Haris1977** [comment]
+1 for this (i have many fba/mame/pc engine roms with thumbnail missing)

**Comment by sselph** [comment]
I added the -missing option where you specify a file and it will output the file name, error, hash and an extra message that is if the game is missing or that there isn't a gdb ID, etc.
