### ISSUE TITLE
change directory

### ISSUE THREAD

**Issue by Tyrsus666** [sselph/scraper#57]
sorry for my bad English.
i am using an rpi2 with retropie your scraper always tells me that it could not find any rom directory.

**Comment by Haris1977** [comment]
Is cd ~/RetroPie/roms/ working?

**Comment by Tyrsus666** [comment]
I will give it a try tomorrow

**Comment by Tyrsus666** [comment]
no
the scraper searches in /root/RetroPie/roms/ but the RPI2 path is /home/pi/RetroPie/roms

**Comment by Haris1977** [comment]
Redownload retropie (latest version) from here: http://blog.petrockblock.com/retropie/retropie-downloads/

Then ssh to your pi and download the scrapper by:

wget https://github.com/sselph/scraper/releases/download/v1.0.4/scraper_rpi2.zip

sudo unzip scraper_rpi2.zip scraper -d /usr/local/bin/

Then (e.g for scrapping MAME folder):

cd ~/RetroPie/roms/mame-mame4all  

scraper -mame

**Comment by Tyrsus666** [comment]
This works for me. Thank you.
But now i've got a new problem. Every game gives a hash not found error.
Could you help me out?

**Comment by Haris1977** [comment]
Maybe you do not have the appropriate rom collection?
