### ISSUE TITLE
6 hours scraping >2000 games .. nothing actually showing in ES

### ISSUE THREAD

**Issue by arcooke** [sselph/scraper#59]
I'm at a bit of a loss here.  I followed the instructions on the main github page and ran `./scraper` from the roms folder.  It went through the long process of scraping all my 2000+ games and it took about 6 hours.  I finally loaded back into ES, and images/info isn't showing up on my games.

I have a giant `gamelist.xml` file in `~/RetroPie/roms/` .. and thousands of images in `~/RetroPie/roms/images` ... but they aren't showing up in ES.

The scraper script is in `~/RetroPie/roms`

I checked where the gamelist.xml file should live, and found this:
https://github.com/Aloshi/EmulationStation/blob/master/GAMELISTS.md

It says it checks in each individual console system directory, or in the `[SYSTEM_PATH]` directory, but I don't know where that is exactly.  What am I missing here?

Ignore my edit.. I made another thread and figured out the answer.. figured I would just reuse this thread for a new question instead of creating another.

**Comment by sselph** [comment]
Sounds like you ran the script from ~/RetroPie/roms/ so it scraped every system and made one large gamelist.xml file. You can do scraper -scrape_all to do the same thing but it will place the gamelists and images in each emulator's folder. The alternative is to cd to the system you want to scrape and run the scraper from that directory.

**Comment by aaronbond** [comment]
i'm half way through a scrape, if i scrape all will it mean re downloading everything i've already done?

**Comment by sselph** [comment]
If you press ctrl+c once it will say it is stopping then stop gracefully. If you add the -append flag it willl skip any file already in the gamelist.xml and even without the -append flag it won't re-download images which is the thing that typically takes the most time.

As for integrating in to ES I did that with:
https://github.com/Aloshi/EmulationStation/pull/355

It is only in the unstable branch and is a little old now.

**Comment by aaronbond** [comment]
ah excellent, again great work on this.
