### ISSUE TITLE
Add Atari Lynx Support

### ISSUE THREAD

**Issue by ProxyCell** [sselph/scraper#6]
Now that the Atari Lynx is being emulated in RetroPie could support for atari lynx games in this scraper be given support for their games?

**Comment by sselph** [comment]
Sure there are only 65 games in thegamesdb so won't be a ton of work, but I don't know if that will leave a disappointingly number of games unscraped. What are the supported rom extensions, I don't have lynx in my es_systems.

**Comment by ProxyCell** [comment]
well thats alright, in the entire English No-Intro set there are only 85 roms
they use the .lnx extension

**Comment by sselph** [comment]
Added support for lnx and lyx(raw lnx without a header) and updated my hash DB with the new entries.
