### ISSUE TITLE
Set image/description resource server alternative to thegames.db

### ISSUE THREAD

**Issue by edulemasson** [sselph/scraper#62]
The GamesDB is down!
So we can use different ones servers like http://archive.vg/

**Comment by sselph** [comment]
The database I created is a list of hashes to the ID in thegamesdb so adding a different source is non-trivial. I used to host a cache of thegamesdb but they have improved the stability so took it down. If the reliability starts being an issue I can work on reimplementing my cache.

I did add the ovgdb which you can use with -use_ovgdb=true This had its own mapping of hash to rom data but it probably isn't as complete. If someone wants to go ahead and create another mapping of hash to ID of another DB or create a cache, I can see about integrating it.

Also archive.vg, I can't see any way to create an account or get an API key for the API. Also there is no longer even a link for a documented API.
