### ISSUE TITLE
Running scraper from retropie-setup

### ISSUE THREAD

**Issue by dcteal** [sselph/scraper#64]
I have a few questions in regards to running the scraper from the retropie-setup / experimental packages menu. 

1 - how do you killall emulationstation processes without killing the session you're in to run the scraper?  As soon as I issue the 'kickall emulationstation' from an ssh session it kills my session in the retorpie-setup

2 - Is there anyway to setup switches before scraping?  (i.e. -thumbs_only)

3 - what version of GoLang is the scraper in the retropie-setup / experimental packages menu using?  When I issue command - go version, it returns that there is no version of Go.

**Comment by sselph** [comment]
1. I haven't ever used it from the retropie menu but don't see why killing emulationstation would kill the setup program. Maybe if it was being run from inside of ES. If you are really concerned, you can exit ES then press a key to keep it from rebooting then run the setup script outside of ES.

2. No, They have preset some of the flags. If you want to do something different you'll have to run the scraper yourself. They set -mame_img t,m,s -thumbs_only -workers 4.

3. I compiled the latest version using Go 1.5.3. If you are using this version it doesn't require you actually have Go installed. You'd only need it if you were compiling it yourself. I've precompiled it and everything is statically linked so you don't need anything other than the program.
