### ISSUE TITLE
403 Forbidden Response

### ISSUE THREAD

**Issue by Robakero** [sselph/scraper#65]
I have used your excellent scraper for months - thank you.  I have now upgraded to the latest retropie and installed the scraper as per the instructions and all went well as it normally does.  This is a fresh install on a clean retropie 3.4 image for raspberry pi2.  When I run the scraper, I get:

403 Forbidden response
panic: runtime error: invalid memory address or nil pointer dereference

Followed by loads of other stuff (attached).  Am I doing something wrong?

Thanks
![error](https://cloud.githubusercontent.com/assets/17035426/12767659/6446bb36-ca02-11e5-9495-3d21b6079b89.jpg)

**Comment by sselph** [comment]
Okay the panic is me not properly handling the 403 error that is returned. I'll clean that up. The 403 is odd I have the ACL on those files set to public and I just tried it and it worked. Can you see if it is working now?

**Comment by sselph** [comment]
NM I was able to reproduce this. I have run out of free quota for serving the files

**Comment by sselph** [comment]
Found the issue. I disabled a feature that I had a long time ago where I was caching the thegamesdb and people could use it as a source of data. I guess I forgot to disable the endpoints on my server and someone is using a very old build or something started crawling the site and found it. So it ate up all my quota.

In 8h the quota should reset. I apologize for the inconvenience.

**Comment by moreirawebmaster** [comment]
just run the scraper -thumb_only command and returned me the message got 403 Forbidden response, any idea what is happening and may the day of correction?

**Comment by sselph** [comment]
As I mentioned previously, someone used up all my quota on my Google account and in 3h the quota will reset and everything will start working again. I have deleted all the files and removed the urls that were used so this shouldn't happen again.

**Comment by Robakero** [comment]
Thank you for your help with this, great.  Its working perfectly.
