### ISSUE TITLE
scraper fails if rom dir is a symbolic link

### ISSUE THREAD

**Issue by MisterTea** [sselph/scraper#66]
I have all of my rom dirs as symbolic links.  filepath.Walk(...) does not follow symbolic links as per https://golang.org/pkg/path/filepath/#Walk

To fix, add this line as the first line of Scrape(...):

```
xmlOpts.RomDir, _ = filepath.EvalSymlinks(xmlOpts.RomDir)
```

**Comment by sselph** [comment]
Thanks. I've made the change.

**Comment by MisterTea** [comment]
Thanks!!!
