### ISSUE TITLE
error - command not found when I run - scraper from rom directory

### ISSUE THREAD

**Issue by dcteal** [sselph/scraper#68]
Not sure what I'm doing wrong.  

Downloaded - scraper_rpi2.zip to my PC, unzipped the file and used WinSCP to transfer the file 'scraper' to my roms directory (i.e. ~/RetroPie/roms/atari2600).  

Then from the command line, I enter - pi@retropie:~/RetroPie/roms/atari2600 $ scraper -thumb_only and I get an error '-bash: scraper: command not found'

What am I missing?

**Comment by robertybob** [comment]
Are you using the Terminal within WinSCP or using Putty? If Putty then for me I type:

cd/ROM DIRECTORY

Followed by: 

scraper -thumb_only 

I don't bother with the $ and I do the two commands separately so I know I'm running it in the correct directory.

**Comment by sselph** [comment]
If you want to run from a directory that is not in the path like the rom directory you have to give the full path. So that looks like:
`./scraper -thumb_only`

**Comment by dcteal** [comment]
Using ./scraper -thumb_only worked great!  Thanks.

**Comment by dankcushions** [comment]
not sure where else to put this, but this issue came up in my googling to a similar issue:

i nstalled the scraper in /home/pi, but it refused to run when i navigated to `/home/pi/roms/RetroPie/arcade` (didn't try others). got around this by running: 
```
pi@retropie:~/RetroPie/roms/arcade $ ~/scraper -mame -mame_img "s,t"
```
might help someone else..
