### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by avedianj** [sselph/scraper#70]
I followed all install steps but when I run scraper for one single or all rom directories i get this:
INFO: Checking for new MAME history.
Get https://storage.googleapis.com/stevenselph.appspot.com/hash.csv.gz: x509: certificate signed by unknown authority

**Comment by sselph** [comment]
Hmm it would be odd to get that error. The server and certificate would be Google so those should be known. Is this problem persisting? are you in an odd environment like a corporate network that might be proxying SSL traffic? Is the date set correctly on the device you are using?

**Comment by avedianj** [comment]
I'm just on a normal home network. Problem is persisting. Date/time are
correct.

**Comment by sselph** [comment]
A couple more questions. What OS is the scraper being run on? If it is linux/mac can you try running `openssl s_client -connect storage.googleapis.com:443` to get the cert chain. It should look like
```
---
Certificate chain
 0 s:/C=US/ST=California/L=Mountain View/O=Google Inc/CN=*.storage.googleapis.com
   i:/C=US/O=Google Inc/CN=Google Internet Authority G2
 1 s:/C=US/O=Google Inc/CN=Google Internet Authority G2
   i:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
 2 s:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
   i:/C=US/O=Equifax/OU=Equifax Secure Certificate Authority
---
```
You can also try downloading the file using a browser or wget https://storage.googleapis.com/stevenselph.appspot.com/hash.csv.gz

**Comment by avedianj** [comment]
Retropie on raspberry pi. I figured it out and am embarrassed I didn't
figure this out before. I have my home network setup with parental
controls. I never turned them off for the rpi's IP. That's what caused the
issue. Now thegamesdb is down so it still isn't scraping but i think we
solved the main issue here. Thanks for your patience and of course for your
efforts in providing this feature to us all.
John

**Comment by sselph** [comment]
Glad you figured it out.
