### ISSUE TITLE
Weird issue on a specific iso ROM

### ISSUE THREAD

**Issue by nerdythor** [sselph/scraper#71]
So my PSX roms for the most part are .bin files but two of them are .iso. They play fine, but scraper completely overlooks them. I even manually added their hash to the .csv and while that worked for a few games these ones just do not get scanned. Is there plan to support .iso or is this something else?

**Comment by sselph** [comment]
Yeah as you noticed iso isn't a supported format on any system so it ignores it if you've added the hash to the csv you can do -extra_ext=".iso" to force it to look at them.

**Comment by nerdythor** [comment]
Sorry sselph... I should've said .img it looks like. Would the same -extra_ext=".img" work or is it unneccessary?

**Comment by sselph** [comment]
yeah if there is any extension that the scraper is skipping that you want to force it to look at you can use `-extra_ext=".iso"` and can even pass more than one `-extra_ext=".iso,.img"`
