### ISSUE TITLE
Support for Colecovision

### ISSUE THREAD

**Issue by psadier** [sselph/scraper#72]
Please add support for ColecoVision roms

Thanks,

**Comment by stevetb** [comment]
@sselph = If you setup this platform I will generate the hashes and link to TheGamesDB

**Comment by sselph** [comment]
Support has been added for the extension .col. I added all the games in thegamesdb that I could find a match for in the no-intro set. I will leave this open for a while for any follow up hashes.

**Comment by stevetb** [comment]
@sselph I will be out of town for a week.  When I return I will start the process of scraping all the roms & variations of roms I can find.  Redump will be a guide as well to ensure I capture everything.  Thank you again for your help and your excellent scraper!!!!!

**Comment by stevetb** [comment]
@sselph Starting on this set now.  Give me a few days to complete.

**Comment by stevetb** [comment]
@sselph It looks like you did most of the hard work!  There were a few holes left within the No-Intro Romset which I have filled in.  After there are entered I will verify and then we can mark this as completed.

https://drive.google.com/open?id=1KEU1c_etVgPs8tOKiRSWcCa-GXV_D-SjuCRoWliPr1k

**Comment by sselph** [comment]
Added

**Comment by stevetb** [comment]
@sselph I just re-ran and it looks like the titles I added are still not showing up for ColecoVIsion.  I also checked your CSV and did not see them in there either.

**Comment by sselph** [comment]
Thats odd. I just downloaded it to make sure and I see 173 and all have an ID

**Comment by stevetb** [comment]
Let me wipeout all of my gamelists and regenerate.  Hopefully its me.

**Comment by stevetb** [comment]
@sselph The issue was on my end.  I still had an images folder in the roms directory for coleco after I created the .CSV for all missing files.

**Comment by stevetb** [comment]
I think we can now mark this off as completed.  Thank you sselph!
