### ISSUE TITLE
Can I run with only text files ?

### ISSUE THREAD

**Issue by mbribeiro** [sselph/scraper#75]
I am building a [Docker](https://www.docker.com/) container to scrap descriptions and images and I would like to feed scraper not with a directory containing roms but with a text file with the same information it needs to scrap a rom.

Does anyone know if I can do this right now this scraper ?
I would be great if I simply build a gamelist and send to a scraper server.

Thanks in advance.

**Comment by sselph** [comment]
Nothing like that can be done with the current code as is. The script uses the file's hash and the file name to do the look up and generate the gamelist. So it would be possibly to use something like the [shasum](https://github.com/sselph/scraper/blob/master/shasum/shasum.go) tool I wrote and have the server use that to generate the gamelist and get the images to the client.

You could also do something like skip the image and data download and generate the xml file. I add in the source and ID in to the xml so you could have the server parse that and then do the look ups and downloads.

Either way requires some custom built code.
