### ISSUE TITLE
Hash Generation Command for Scraper

### ISSUE THREAD

**Issue by stevetb** [sselph/scraper#76]
Running RetroPie 3.7, I am unable to run the below command.  Is there a more updated command which we can use for RetroPie 3.7 to generate a list for our un-scraped roms to submit for entry?

This command was from Wiki and appears to be outdated:
```
cd /ROM DIRECTORY
scraper -thumb_only -missing file -workers 4
```

**Comment by HerbFargus** [comment]
Its  likely because its not installed in the rom folder or universally so you'd have to call it from its main folder. ie.:

```
cd /ROM DIRECTORY
/opt/retropie/supplementary/scraper/scraper -thumb_only -missing file -workers 4
```

**Comment by stevetb** [comment]
It worked!  Well.............kinda.  I received this lovely message:

"It appears that thegamesdb.net isn't up.  If you are sure it is use -skip_check to bypass this error."

Now if I had $1 for everytime TheGamesDB went down, I'd be rich!

**Comment by sselph** [comment]
Thanks @HerbFargus I was wondering where retropie was placing the binary.
