### ISSUE TITLE
Feature Request - create log

### ISSUE THREAD

**Issue by LodanZark** [sselph/scraper#77]
Is it possible at some point in the future to add an option to generate a log file to list it up which games have missing images and which games haven't been identified by the database?

Thanks for make available this awesome tool ;)

**Comment by sselph** [comment]
There is the `-missing file.csv` flag it will write to a csv and mention if the image is missing, if the hash is identified and missing in thegamesdb, etc.

Let me know if that works.

**Comment by stevetb** [comment]
@LodanZark I would suggest reading the Wiki for how to add missing files to the database:

https://github.com/sselph/scraper/wiki/Scraper-can't-find-a-game%3F

**Comment by LodanZark** [comment]
Well I guess the problem I got was unable to open csv with nano over command line, I guess I will use the csvkit ;) thanks for the advice
