### ISSUE TITLE
Add Virtual Boy Scraper Support

### ISSUE THREAD

**Issue by stevetb** [sselph/scraper#78]
@sselph = If you setup this platform I will generate the hashes and link to TheGamesDB

**Comment by sselph** [comment]
Support has been added for the extension .vb. I added all the games in thegamesdb that I could find a match for in the no-intro set. I will leave this open for a while for any follow up hashes.

**Comment by stevetb** [comment]
@sselph I will be out of town for a week.  When I return I will start the process of scraping all the roms & variations of roms I can find.  Redump will be a guide as well to ensure I capture everything.  Thank you again for your help and your excellent scraper!!!!!

**Comment by stevetb** [comment]
VirtualBoy is compete!  All hashes from No-Intro Romset correctly match to TheGamesDB.

Thank you sselph!
