### ISSUE TITLE
Add NeoGeo Pocket Color Scraper Support

### ISSUE THREAD

**Issue by stevetb** [sselph/scraper#79]
@sselph = If you setup this platform I will generate the hashes and link to TheGamesDB

**Comment by sselph** [comment]
Support has been added for the extension .ngpc. There are no hashes in the no-intro set so will add any hashes you have.

**Comment by stevetb** [comment]
@sselph I will be out of town for a week.  When I return I will start the process of scraping all the roms & variations of roms I can find.  Redump will be a guide as well to ensure I capture everything.  Thank you again for your help and your excellent scraper!!!!!

**Comment by stevetb** [comment]
@sselph instead of .ngpc all roms are listed in .ngc format.  Could you instead add this?

**Comment by sselph** [comment]
oops copied the folder name instead of extension from the wiki. I'll fix that real quick.

**Comment by sselph** [comment]
Fixed and released.

**Comment by stevetb** [comment]
@sselph Below is the completed No-Intro Romset for Neo Geo Pocket Color:

https://drive.google.com/open?id=1zOPTHdEGur0YQldCuVgluMe3Nq82j4-CEoKjM72WUTg

Please add when you can and I will verify.

**Comment by sselph** [comment]
Added

**Comment by stevetb** [comment]
@sselph Looks perfect, thank you for adding.

We can close this and call it now supported.
