### ISSUE TITLE
Add Sega SG-1000 Scraper Support

### ISSUE THREAD

**Issue by stevetb** [sselph/scraper#80]
@sselph = If you setup this platform I will generate the hashes and link to TheGamesDB

**Comment by sselph** [comment]
Support has been added for the extension .sg. I added all the games in thegamesdb that I could find a match for in the no-intro set. I will leave this open for a while for any follow up hashes.

**Comment by stevetb** [comment]
@sselph I will be out of town for a week.  When I return I will start the process of scraping all the roms & variations of roms I can find.  Redump will be a guide as well to ensure I capture everything.  Thank you again for your help and your excellent scraper!!!!!

**Comment by Redemp** [comment]
@stevetb
Thank you for taking your time to do this. What romsets are you using to add the missing hashes?
No-Intro, Tosec, Redump, Truerip?

@sselph Let me know if there is anything I can do to help with this.

**Comment by sselph** [comment]
I've added every game I could see in thegamesdb that was in the no-intro set. Other than testing to see if some of the ones I matched are working, you can take a look at https://storage.googleapis.com/stevenselph.appspot.com/hash.csv.gz the games where column 3 is 4949 and column 2 is empty are ones I didn't see in thegamesdb. If you want to create entries in thegamesdb and fill that column in, that'd be great.

**Comment by stevetb** [comment]
All No-Intro Romset titles have been added to TheGamesDB and hashes have been sent.  Please add when you can and I will verify from my end.  All TheGamesDB titles were also updated so they are consistent to my additions.

Here is my CSV, please add when you can:
https://drive.google.com/open?id=1h2ljwPz7F7_ucF8TQ5KeLeoe3nMHab_Iqj5Q1hLS0j8

-Steve

**Comment by stevetb** [comment]
@Redemp at first I was using the "whatever I can find on the internet approach" which made it difficult.  I have switched to only using the No-Intro Romsets as they perfectly match what I personally am wanting with my collection.

-Steve

**Comment by Redemp** [comment]
@stevetb

I do to. This must have been a massive job to pull off and I as many other's thank you for you're contributions. I'm looking forward to you're contributions to the rest of the missing no-intro sets that's missing. 

Thank you!

**Comment by sselph** [comment]
Thanks! I added them in and uploaded the changes.

**Comment by stevetb** [comment]
@Redemp Thank you very much.  I know this is one of the systems that gets little to no love, so I thought I would put some polish onto it.  

I have only recently gotten into the No-Intro Romsets so I have been a bit sidetracked with those.  But, I am now moving onto SNES and completing the .csv to give to sselph.  I should be done soon, then we can mark that off as "No-Intro" complete as well, hehe.

Glad you liked it, it was fun!

-Steve

**Comment by stevetb** [comment]
@sselph dang!  You are fast!  Thank you!

I updated my scraper, ran the SG-1000, and then verified the scraper information.  Everything I can see is perfect.  There are some art changes I have submitted with TheGamesDB which have not been approved yet, but that is outside of what your script needs to do.  Once those are approved on their end I would consider this perfect to the No-Intro Romset for SG-1000.

Thank you again, your amazing!

Next up will be SNES for me.  I found 11 or so roms which I will be submitting a .csv for tonight or tomorrow.  Once that is complete, I think we can say SNES is No-Intro Certified as well.

I have also updated the Wiki to show your scraper now has support for SG-1000 and Virtual Boy, since they are both 100% complete.

I am submitting a close for the SG-1000 issue.

-Steve

**Comment by sselph** [comment]
@stevetb Badass. Thanks for doing this work. You and @robertybob have done a true service. It is one thing to say this matches this thing already in the DB. It is another to actually fill in all the blanks and upload images, add descriptions etc.

Keep up the good work.

**Comment by robertybob** [comment]
@sselph Thanks! After all the matching and blank-filling, I'm going to be so pissed off it thegamesdb.net ever goes down for good !
