### ISSUE TITLE
Add No Intro False Option

### ISSUE THREAD

**Issue by dustloop** [sselph/scraper#82]
I love that the scraper is in the setup portion of Emulationstation/Retropie now. 

Would it be possible to scrape with the use no intro false command? I already have my games organised into regional folders so I don't need to see the regions on the game titles unless I just need to do it manual for now?

**Comment by sselph** [comment]
This flag exists you can use it by adding `-use_nointro_name=false`

**Comment by dustloop** [comment]
How do I do that from the setup menu in the retropie setup or would I have install manually then run the script?

**Comment by HerbFargus** [comment]
It's not @sselph's responsibility to maintain the RetroPie scripts. If you want something coded custom then feel free to discuss in the appropriate place on the RetroPie forum: https://retropie.org.uk/forum/

**Comment by sselph** [comment]
Ah yeah sorry I misunderstood, what @HerbFargus said. You can discuss with them to have the feature added or manually invoke the script which it downloads to `/opt/retropie/supplementary/scraper/scraper`
