### ISSUE TITLE
How to find hashes for specific platform?

### ISSUE THREAD

**Issue by stevetb** [sselph/scraper#83]
What would the command be to run scraper through a specific platform, in my case SNES, and have it create a list of all known hashes and then save them to a file.  Similar to what we are doing with the flag:  -missing SNES.csv

Anything similar to identify known hashes?

**Example used for -missing:**
/opt/retropie/supplementary/scraper/scraper -thumb_only -missing file.csv -workers 4

**Why do I ask?**
I have found a few SNES No-Intro Roms where the TGBD reference is incorrect.

Examples for SNES:
* NFL Quarterback Club (USA)
* Star Fox - Super Weekend (USA)

**Comment by sselph** [comment]
That sucks. I tried not to create false positive but It is possible. There isn't a scraper command, but you can download the master csv and filter it. And send updates against it.

For snes on linux it would be something like this to get all the known hashes for snes. In the early days I didn't fill in the platform for roms that didn't have a match but I do my best to sort this all out when hashes are submitted so it might not be 100%.
```shell
wget https://storage.googleapis.com/stevenselph.appspot.com/hash.csv.gz
zgrep ,6, hash.csv.gz
```
But in general download/extract it then search for third column being 6(for snes)

**Comment by stevetb** [comment]
That worked!  I added the two missing hashes here:

https://drive.google.com/open?id=1bAlg3rX94vdgqWdY3XPh3dMZMQ2sL8ZlADZnb903ono

**Comment by stevetb** [comment]
Using your .csv I also found 3 other roms for NFL Quarterback Club which should also point to TGBD ID 5707 instead of 5706.  It's all in the .csv I just posted.

**Comment by stevetb** [comment]
Are you okay if I post that link to the Wiki?

**Comment by sselph** [comment]
the link to the hash.csv? Sure it is in the code.

**Comment by stevetb** [comment]
Done and done, let's close this thread.
