### ISSUE TITLE
Add Support for Vectrex

### ISSUE THREAD

**Issue by stevetb** [sselph/scraper#84]
@sselph I would like to add support for the General Consumer Electronics - Vectrex.  This system is currently supported by RetroPie and gets little love.  Since there are only 45 No-Intro ROMs associated with this system it will be an easy one to complete overnight.

The file extension is .vec

**Comment by sselph** [comment]
Added .vec and .gam since they are both listed here:
https://github.com/RetroPie/RetroPie-Setup/wiki/Vectrex

**Comment by stevetb** [comment]
@sselph Thank you, I am almost done with Intellivision.  This will be my next platform.

**Comment by stevetb** [comment]
@sselph Try this on your end when you can.  When I ran the missing hash generation my file is empty except for the header in the file.

**Comment by sselph** [comment]
It seems to work for me. Do you see the errors from it not finding the hashes?

**Comment by stevetb** [comment]
@sselph My bad, I needed to update the scraper to the latest version.  That seemed to fix this issue.

**Comment by stevetb** [comment]
@sselph Here is the complete No-Intro Romset for Vectrex.  All ROMs from the Romset have been added.  I have removed the file extensions for the name but otherwise kept the name exactly as it is for No-Intro.  Please let me know of any corrections I need to make.

https://drive.google.com/open?id=1fqT4FTz_hDnhRpFrf-iToeA3b2itCS9vdhIDUFjN7h4

**Comment by sselph** [comment]
Done

**Comment by stevetb** [comment]
This looks great!  Thank you.  I'm going to close this out and I think we can say it's now supported.

**Comment by paradadf** [comment]
@sselph This game needs to be updated. It appears that the linked game was a duplicate. Here the corrected GDB ID:
StarHawk (World) - d6b388b3951e34971c1b00c7fdf8dd00ad52df0932804 - 32804

**Comment by sselph** [comment]
@paradadf Sorry I missed this. I also messed up and didn't actually upload the files from yesterday so this should be fixed.
