### ISSUE TITLE
Support for Atari 7800

### ISSUE THREAD

**Issue by BenWlson** [sselph/scraper#85]
If you could please add support for Atari 7800, I will supply the HASH data and GamesDB links.

~/RetroPie/roms/atari7800
*.a78 *.bin

**Comment by stevetb** [comment]
@BenWlson Make sure you are using the No-Intro Romsets.  Linking to the existing TGDB files is pretty straight forward.  The hardest part I have found is adding games to TGDB which do not exist.  Artwork can be hard to find and often needs to be cropped to show the cover scan only.  Make us proud bud!

**Comment by BenWlson** [comment]
The .a87 extension needs to be added so I can generate a csv file from my roms.

**Comment by sselph** [comment]
I'm seeding this with no-intro data the only one that did quite match was
`c44fe244206590abc26fbbd520a5726353899e35,22379,27,Baseball (Europe)`
I matched it to Pete Rose Baseball which is a clone of the game.

The .a78 seems to include a header not in the no-intro hash so added logic to try and detect and remove it.

**Comment by BenWlson** [comment]
All my games scraped successfully. Thanks.
