### ISSUE TITLE
Add Support for Magnavox Odyssey²

### ISSUE THREAD

**Issue by stevetb** [sselph/scraper#86]
@sselph  I would like to add support for the Magnavox Odyssey².  This system is currently supported by RetroPie.

The file extension is .bin

**Comment by sselph** [comment]
The .bin extension is already supported. Let me know if the hashes aren't matching the no-intro hashes and I can add see if I need to do any striping of headers etc. I probably won't need to since bin typically indicates a plain binary.

**Comment by stevetb** [comment]
@sselph Sounds good.  I am planning on going through quite a few platforms over the weekend.

**Comment by stevetb** [comment]
@sselph I tried running this today through the setup script (which I updated prior to running) and it failed (No Hashes Found Errors).  I then tried running this manually as well, same errors and no CSV generated in the end.  The folder these are in is videopac.  Please look at this when you have a moment and hopefully we can fix it.  I can match everything up at that point.

**Comment by sselph** [comment]
Seems to work. I went ahead and added what I could match using my scripts and spreadsheets.

**Comment by stevetb** [comment]
Here you go, all the other no-intro titles for Odyssey 2.  I will check when you add them.  Not sure why I could not see them before.  Updating this time seemed to pull in the titles.  Maybe it needs a single title added before it can detect on the RetroPie, just a guess though.

https://drive.google.com/open?id=1scBpDyuhcL6Yh0zVmWjOdMSbhjJ7ZVoxjdBLjylF9Ks

**Comment by sselph** [comment]
Thanks! These have been added. Let me know if there are any issues.

**Comment by stevetb** [comment]
@sselph This turned out perfectly!  Thank you!  I will close.
