### ISSUE TITLE
Add Support for Atari 5200

### ISSUE THREAD

**Issue by stevetb** [sselph/scraper#87]
@sselph  I would like to add support for the Atari 5200. This system is currently supported by RetroPie.

The file extension is .a52

**Comment by sselph** [comment]
Added what I could match

**Comment by stevetb** [comment]
@sselph It looks like only 5 titles were left to add.  Please add when you can then we can close and mark this as completed, yay!

https://drive.google.com/open?id=1HxsVnWyiUJhLMMIZdXFV2WNGC3M45HMGPG6gCSQ2e2g

**Comment by sselph** [comment]
Thanks! These have been added.

**Comment by stevetb** [comment]
Verified, these are all correct.  Thank you @sselph!
