### ISSUE TITLE
Add Support for Atari Lynx

### ISSUE THREAD

**Issue by stevetb** [sselph/scraper#89]
@sselph  I would like to add support for the Atari Lynx. This system is currently supported by RetroPie.

The file extension is .lnx

**Note:**  That is LNX

**Comment by BenWlson** [comment]
Atari Lynx is already supported. Complete US romset scrapes no problem.

**Comment by sselph** [comment]
Yeah it should be there already but if there are missing games feel free to submit them otherwise you can close this out.

**Comment by stevetb** [comment]
Great to know, I will run through Lynx over the weekend with the No-Intro Set and post up a CSV for anything which is missing.  I'll close this out after that pass is completed.

**Comment by stevetb** [comment]
@sselph This set is perfect.  Thank you!
