### ISSUE TITLE
No Images Post Scraping When Viewed

### ISSUE THREAD

**Issue by stevetb** [sselph/scraper#91]
@sselph I found this on Reddit.com.  I too am seeing this for some folders in my build so I don't know of a clear solution to offer to this person
-Steve

https://www.reddit.com/r/RetroPie/comments/4l9l4p/problem_using_steven_selphs_scraper/

Problem:
I'm having some issues trying to scrape all of my roms.

I started using the built in scraper in RetroPie but realized it was going to take way too long to do one by one. I exited retropie (using F4) and ran the retropie setup script and ran Selph's scraper. After it finished I rebooted and my games list shows up the same as before, with only the handful of scraped games I did originally showing up right. When I go into Raspbian I can see it downloaded all the images for the roms to 

/opt/retropie/configs/all/emulationstation/downloaded_images

but for some reason isn't using them in RetroPie.

Any ideas how to fix this?

**Comment by stevetb** [comment]
For me, I believe my issue is that I did not also remove the gamelists.xml file from within my roms folders after scraping.  I think I still have a few of those in my roms folders which were generated which I was scraping for missing titles.  I will verify tonight, but I feel confident that is my issue.

**Comment by sselph** [comment]
Couple things it might be. Was EmulationStation shut down? It sounds like it might have been but if it is running then when it shuts down it write what it had in memory to disk. Good news is the thing that normally takes the most time is downloading images and the scraper won't overwrite those so might be quick to fix.

I saw your update pop up as I was typing this and that is the second option is that the one in the ROM folder takes precedence over the one in the gamelists folder. Good news is deleting the rom folder gamelist will immediately fix the problem.

**Comment by sselph** [comment]
Another possibility is there were issues with RAM or something when there were tons of images. It manifests as nothing really working then you remove one system and everything works again. So if you try just renaming a few of the systems gamelists(so ES won't load them). You might see it click and start working after you hit some magic number. This was an old issue and may be resolved but just a thought if nothing else works.

**Comment by stevetb** [comment]
When running the scraper through the front end when ES is running I believe it denies running the scraper.  I tried this through Putty as well and if ES is running on the PI then the error comes up in putty as well.  It looks like the safeguards for running scraper are good from what I am seeing.  My bet would be that gamelists.xml exists in the rom folder, I am sure that is my particular issue when thinking about it.

**Comment by stevetb** [comment]
@sselph Here is another thread you may want to look at:

https://www.reddit.com/r/RetroPie/comments/4l4dao/question_about_stephen_sselph_scraper/

**Comment by sselph** [comment]
turned out to be missing parent folder of gamelist. Resolved by commit 3afc55db5ca484524c7994e107cc853f91aa4d18
