### ISSUE TITLE
Add Support for Neo Geo

### ISSUE THREAD

**Issue by stevetb** [sselph/scraper#92]
I would like to have the Neo Geo platform added.  The default extension for Neo Geo is .zip

https://github.com/retropie/retropie-setup/wiki/neo-geo

Please add and I will go through TGDB and connect all.

**Comment by biscuits99** [comment]
Would this already be included via mame?

**Comment by BenWlson** [comment]
It is currently supported via MAME, but therefore has limited descriptions and only screenshot images for cover art. Thegamesdb has proper info for the home console AES version of NeoGeo, so it would be nice to scrape actual boxart images.

**Comment by sselph** [comment]
This one will be a little tricky. Normally when I encounter a .zip file I look inside for a ROM extension I recognize and hash that. So in this case I guess I would need to hash the zip file itself. What is in the zip files? Are there multiple files or a single file? Is there some uniformity like every one contains a set number of files or files named a certain thing that I might be able to has instead of the zip or to determine if this is a neogeo zip?

**Comment by stevetb** [comment]
In the .zip file I am seeing multiple .bin files inside.  It looks like number of C1/C2/C3/C4 files varies per .zip file.  Same can be said with the V1/V2/V3 files.   There is only a single .zip file per title. 

**Here is an example of file names for 3 Count Baseball:**
043-c1.bin
043-c2.bin
043-c3.bin
043-c4.bin
043-m1.bin
043-p1.bin
043-s1.bin
043-v1.bin
043-v2.bin

**Here is an example of Age of Fighters:**
044-c1.bin
044-c2.bin
044-c3.bin
044-c4.bin
044-m1.bin
044-p1.bin
044-s1.bin
044-v2.bin
044-v4.bin

**Here is an example of Age of Fighters 2:**
056-c1.bin
056-c2.bin
056-c3.bin
056-c4.bin
056-c5.bin
056-c6.bin
056-c7.bin
056-c8.bin
056-m1.bin
056-p1.bin
056-s1.bin
056-v1.bin
056-v2.bin
056-v3.bin

**Comment by stevetb** [comment]
@biscuits99 It looks to be supported, but as @BenWlson said, it pulls the MVS platform and not the AES platform for information.  TGDB has a NeoGeo Section so that would be ideal to use I would think.  Even if there is redundancy with MAME.

**Comment by biscuits99** [comment]
You may also need to consider that the contents of the zip files have the possibility of changing depending on what the arcade emulator & version you are running requires, lr-mame-2003, pifba, gngeo etc....
So I imagine safer to rely on the zip name that wont change, and have a flag for neogeo to avoid pulling any duplicates from mame. That way you could scrape these for mame or neogeo.

**Comment by sselph** [comment]
Ah okay. I guess I could use the same approach as daphne and scumm where the filename is the key and we just ignore the hash.

**Comment by stevetb** [comment]
Sounds good, I can match up to TGDB if you need my help.

**Comment by stevetb** [comment]
Hopefully this helps.  I tracked down all of the NeoGeo TGDB ID's.  Then I matched them all up to the .zip file names.  Some files I found two versions were available so I made a second column and called it "ZIP Name Alternate".

https://drive.google.com/open?id=1FISIrcVIQuWcUUh09Q6008Rws8EJtYBbh0PpCbENPbY

**Comment by sselph** [comment]
Thanks, I've added these.

**Comment by stevetb** [comment]
For me, I am not seeing any artwork for most of the NeoGeo games after scraping is completed on my RetroPie.  A few show artwork but it appears to be from the MAME section since it is screenshots only of the games, not the AES console artwork for this platform which exists on TGDB.

Here is a list of the art which was scraped incorrectly from the Arcade section instead of NeoGeo Console.  This is the only art which shows for my RetroPie:

* 2020 Super Baseball
* Art of Fighting
* Ganryu
* Ghost Pilots (NGH-020)(US)
* Ghost Pilots (NGM-020)(NGH-020)
* Jockey Grand Prix (SET 1)
* Karnov's Revenge
* King of the Monsters (SET 2)
* Magician Lord (NGH-005)
* Metal Slug
* Metal Slug 2
* Metal Slug 3
* Metal Slug 4
* Metal Slug 5
* NEO-GEO (Bios File)
* NIghtmare in the Dark
* Pochi & Nyaa
* Power Instinct Matrimelee
* Samurai Showdown / Samurai Spirits (NGH-045)


What I am seeing could be what others on Reddit/RetroPie are seeing when they do not see artwork after scraping.  Not sure but hopefully we can look at the below and figure out why its not pulling the artwork correctly.

Here are some details about my particular install:

* Pi3 running 3.7 of RetroPie
* sselph scraper = Ran from command line @ retropie_setup.sh
* sselph scraper = updated twice prior to running
* sselph scraper = no other systems were selected to be scraped, only NeoGeo
* /roms/neogeo only contains .zip files for games.  There were no Images folder or gamelists.xml file in this folder, only roms in .zip format.
* nothing in this directory prior to scraping: /opt/retropie/configs/all/emulationstation/gamelists/neogeo
* nothing in this directory prior to scraping: /opt/retropie/configs/all/emulationstation/downloaded_images/neogeo
* nothing in this directory prior to scraping /home/pi/.emulationstation/gamelists/neogeo
* nothing in this directory prior to scraping /home/pi/.emulationstation/downloaded_images/neogeo

**Comment by stevetb** [comment]
Descriptions appear correctly, however, I am not positive they are from NeoGeo or Arcade as probably both the same descriptions copied over from one to the other when they were created.

**Comment by sselph** [comment]
Ah has to do with the mame image flags. The standard title, snap, marquee, cabinet images. I forgot TGDB returns boxart so would need to do -mame_img="b" if using the -mame flag.

**Comment by sselph** [comment]
I think I fixed it

**Comment by stevetb** [comment]
It worked!  You're friggin' awesome!  Thank you.

Let's not close this quite yet.  There are some titles left which I would like to add which were not on the list above.  After that I think we are set to close and mark as complete.

Thank you!

**Comment by stevetb** [comment]
@sselph Here is a new CSV which I think has most, if not all, of the issues corrected for Neo Geo.  

1.  Please add games 2-7, they are missing
2.  Please correct the names for 8-21.  My apologies I do not have the hash for these, only the filename.

https://drive.google.com/open?id=11W6UZxQtBwyAVuSDpwXvQiYOzDKQxy2MvqapGc6yp48

Thank you!

**Comment by sselph** [comment]
Sorry for the delay but added these.

**Comment by stevetb** [comment]
We still need to update the names for these alternate versions.  I marked the errors in red.

https://drive.google.com/open?id=1eEwboJDG6QtTXgwZA09u7G-7gV0YqnP8Lk5LxVHLjVI

**Comment by sselph** [comment]
Opps I wasn't adding names. I went and fixed that and it will roll out tonight with the rest of the updates.

**Comment by paradadf** [comment]
@sselph I just scraped my neogeo collection in mame mode and noticed that with despite of my flags `-mame -mame_img="s,m,t"` I´m getting mostly logos instead of snaps using v1.1.5.

**Comment by stevetb** [comment]
@sselph well...........good news and bad news.  The good news is the names for the titles in my last .csv are correct so we are good there.  The bad news however is that most of the other titles updated as well and many of these now include Japanese characters at the end of the name in brackets.  We need to remove anything in brackets as they were before last night.

Examples:
Double Dragon (Double Dragon 6-1)
Fight Fever (Wang Jung Wang)
Ganryu (Musashi Ganryuki)

Note:  Please keep all the (Alternate Set) additions which we just added.  Those are correct.

Thank you!  Sorry to be such a pest, haha

**Comment by sselph** [comment]
@paradadf This was because I had the gdb as a higher priority and it doesn't have a ton of screen shots. I moved it down when running in -mame mode.

@stevetb Done. I'll push these out tonight after I check the other issues for updates.

**Comment by stevetb** [comment]
@sselph I won't be able to test on my end for a few days.  I'll report back as soon as possible.  Thank you!

**Comment by paradadf** [comment]
@sselph it works now as intented! Thank you!

**Comment by stevetb** [comment]
@sselph removed downloaded_images and gamelists.xml today. Made sure no other files are in the roms directory from a previous missing scrape.  Updated the script, re-ran scraper for neogeo.  Afterwards, the names I am seeing are for the most part the same as they were for MAME.  The artwork I am seeing reverted back to MAME as well, so only title screenshots and not the boxart which we had been using.

Sorry to be a pest, this platform is proving to be a lot of work.  Sorry :(

**Comment by paradadf** [comment]
On my side using Windows, everything is working well. I get exactly what I ask for, either images or descriptions from the source I choose.

**Comment by stevetb** [comment]
@paradadf I will setup a second Retropie tonight and see if that pulls in the right metadata.

**Comment by stevetb** [comment]
I ran this again inside the roms folder and it scraped everything perfectly.  It appears the issue is on my end and not on the scraper.

@sselph Thank you!  We did it!  I will close this and we can mark this as completed.  Thank you and @paradadf for battling through this to make it perfect.  Great job guys!

**Comment by robertybob** [comment]
@paradadf Some of the Neo Geo rear boxart images you've submitted to TGDB.net include the spine, is there any particular reason for that? You've got 9 such images in the moderation queue but I've not yet approved them for this reason. I was leaving it to another mod to decide but it looks like no one else has noticed these images yet lol

**Comment by stevetb** [comment]
@robertybob are you an Administrator for TGDB?  If so, I really need your help!  I need to have a platform added and have another platform removed.

**Here are the posts:**
http://forums.thegamesdb.net/topic/129/platform-request-texas-instruments-ti-99-4a
http://forums.thegamesdb.net/topic/132/platform-delete-request-r-delete-what-am-i

**Comment by robertybob** [comment]
@stevetb I don't have permissions to delete, but I've renamed that weird platform to the Texas Instruments one. 
http://thegamesdb.net/platform/texas-instruments-ti-99-4a/
Are you able to add details to it, or does a mod like me have to?

**Comment by stevetb** [comment]
@robertybob Thank you!  You have no idea how long I have been trying to get that platform created.  I logged in and it appears that I cannot edit the platform, that is restricted to Administrators only.

How does one become an Administrator for this site?  Is there someone I could contact?

**Comment by stevetb** [comment]
@robertybob I probably have 100 images in the queue too for various games to update the images.  I kinda gave up on attempting to update images because I could never get anyone to approve.

**Comment by robertybob** [comment]
@stevetb I asked kindly when the forums first went up. It seems like the owner only gets involved with the site when it goes down. 
There are currently 8 images in the queue and those are from @paradadf , I remember approving all of yours so they should have been updated. There is a weird glitch whereby deleting an image and reuploading a new one results in the old one still being displayed.

**Comment by robertybob** [comment]
@stevetb Don't give up, I check the moderation queues at least 3 times a week :)

**Comment by stevetb** [comment]
@robertybob thank you.  I really appreciated that!

**Comment by paradadf** [comment]
@robertybob Sorry about the spine for the rear box. I just saw other boxes and did it exactly like that. If that's not right, it would be noce if you could either edit and cut the spine out, or please upload the images elsewhere so I can edit them and reupload again. Sorry about the misunderstanding

**Comment by stevetb** [comment]
@robertybob could you email me?  I would like to discuss more about becoming an administrator for TGDB.  My email address is steve.braaten@gmail.com.

Thank you!

**Comment by paradadf** [comment]
Some missing files to add:

2020bb.zip,1486,24,2020 Super Baseball
b2b.zip,37986,24,Bang Bang Busters
cnbe.zip,28905,24,Codename: Blut Engel
columnsn.zip,37991,24,Columns
diggerma.zip,31598,24,Digger Man
ironclad.zip,1490,24,Ironclad
ltorb1.zip,37993,24,Jonas Indiana and the Lost Temple of RA
neonopon.zip,37994,24,Neo No Panepon
neopong.zip,37996,24,Neo Pong
neotet.zip,37997,24,NeoGeo 2-Player Tetris
ridhero.zip,8676,24, Riding Hero

Still missing (that I noticed) if someone has some time to add them:
neothndr.zip,*GDB ID*,24,Neo Thunder
ngem2k.zip,*GDB ID*,24,NGEM2K
ngfrog.zip,*GDB ID*,24,Frog Feast
poknight.zip,*GDB ID*,24,Poker Night
totcarib.zip,*GDB ID*,24,Treasure of the Carribean
unkneo.zip,*GDB ID*,24,Unknown Neo-Geo Vs. Fighter
vliner.zip,*GDB ID*,24,V-Liner
