### ISSUE TITLE
Add Support for Daphne

### ISSUE THREAD

**Issue by stevetb** [sselph/scraper#93]
Please add Daphne support when you have some time.  The default file extension is .daphne

https://github.com/retropie/retropie-setup/wiki/Daphne

I can connect the files to TGDB when added.

**Comment by sselph** [comment]
According to the wiki page it looks like .daphne is a folder with things in it? Am I reading that correctly? It also looks like it also uses a strict naming scheme like dle21 is a key that tells daphne what game it is. If that is true this seems similar to scummvm and might require some special tooling.

**Comment by HerbFargus** [comment]
Yep you got it. I think the main daphne page has more info on it as the .daphne folder was just a filename we chose for implementing it with RetroPie and emulationstation.

This page I think has all the games and filenames: http://www.daphne-emu.com/mediawiki/index.php/CmdLine

**Comment by sselph** [comment]
Thanks. So what I'll probably do is what I did for scummvm. The "key" will be dle21.daphne instead of a hash and I'll use that to match to thegamesdb. I'll play around with adding this.

**Comment by stevetb** [comment]
@sselph Let me know if you need help with one of them to get it going.  After we have one I can do the rest from there for TGDB to CSV.

**Comment by sselph** [comment]
I can setup a workspace for this. @HerbFargus at http://www.daphne-emu.com/mediawiki/index.php/CmdLine there are entries like lair2_* is that * a wildcard or a literal *?

**Comment by HerbFargus** [comment]
That's  good question. I haven't the slightest, seems three of them have asterisks but I don't know what they mean

**Comment by sselph** [comment]
Okay, If I had to guess it would be a wildcard but like mentioned, it is only 3 so not that big of a deal. I might need to add some code to handle those but will create a workspace for the non-wildcard tomorrow.

**Comment by stevetb** [comment]
I will start building the TGDB titles, if they do not exist currently.  Most I would assume exist currently.

**Comment by stevetb** [comment]
@sselph Here you go!  All of the Daphne titles are now entered into TGDB.  Here is a CSV mapping TGDB to the folder names from the above workspace mentioned above.

https://drive.google.com/open?id=1v1RrTyWejhBpO8UOBWhiILTHUfQyh9tZe_s7IEg4Kqc

**Comment by sselph** [comment]
Sorry for the delay, I was playing around with trying to import my code in to EmulationStation. I've added these so hopefully daphne works.

**Comment by stevetb** [comment]
I added two additional folders to the above list.  Galaxy Ranger and Road Blaster both did not match the folder names generated for me which were created by Daphne.  Please add **galaxyr** and **rb** from the below file.  The other folder names still should remain as options in case others are using them.

https://drive.google.com/open?id=1VQU3GsqHoZVNELzggQiqclTMt-VWC0e3GceaDKBobpo

..............hopefully that all makes sense.

**Comment by sselph** [comment]
Added them anyway.

**Comment by stevetb** [comment]
Looks great, thank you for doing all that you did!

Closing and marking as complete!
