### ISSUE TITLE
Add Support for Game & Watch

### ISSUE THREAD

**Issue by stevetb** [sselph/scraper#94]
I would like to have Game & Watch added. The default extension for Game & Watch is .mgw

https://github.com/retropie/retropie-setup/wiki/Game-&-Watch

Please add and I will go through TGDB and connect all.

**Comment by stevetb** [comment]
@sselph I'll start working on these this weekend.  I have not had good luck though with starting off on a new platform for scraping on a RetroPie.  I will try it but I may need to have you scrape at least one title before the platform will scrape for me.  Not sure why that is, but it seems to happen everytime.  I'll let you know how it goes.

**Comment by sselph** [comment]
Let me know if it is an issue. I can't think of any reason that there has to be 1 valid match before any missing information would be printed but I'll take a look.

**Comment by stevetb** [comment]
It worked great, no issues.  Here is the CSV for everything mapped:

https://drive.google.com/open?id=18ikBTl_ItO062zOambgNrLW5f1b_35bPXOQXcHEkZ9g

**Comment by sselph** [comment]
Sorry for the delay but I've added these.

**Comment by stevetb** [comment]
I made three errors.  Here they are corrected and marked in Red where the error is.

https://drive.google.com/open?id=1rzjZM2-v7zRngSfiAOCLmMlEYCrkfbl6Yj8xyxh5IEM

**Comment by sselph** [comment]
fixing these now will roll them out tonight after getting the rest of the pending updates.

**Comment by paradadf** [comment]
Here are two more games to add:

```
Parachute (Nintendo, Wide Screen).mgw - f435758c55518d7b153e366ba76eda8fe960b1e9 - 33459
Wild Man Jump (VTech, Electronic Tini-Arcade).mgw - 7c9331c4b012738521d082dc9cdf1548b25f0a96 - 36960
```

**Comment by stevetb** [comment]
Name	Hash	Platform	TGDB
Fowling	f4e6c34ee8aab0785436effc49c8bd187e031ae9	4950	**37228**
Pirate	588f5e60ec3640ff92cce6cc925180faa48e70da	4950	**37186**

Please fix the ones in bold above.  They are still pointing to the incorrect TGDB ID's.

**Comment by stevetb** [comment]
@sselph the hashes from @paradadf are different than the ones I have.  I'd keep the names we have setup and just add another hash for those two titles.  After those are added I think we can close this, Yay!

**Comment by paradadf** [comment]
I got mine from https://buildbot.libretro.com/assets/cores/gw/
@stevetb They recently updated Parachute on that site. I had the same hash as you before.
And yes, they should be added as new entries. Thank you very much!

**Comment by sselph** [comment]
@paradadf Added these and will upload them after I check the other issues for updates.

**Comment by stevetb** [comment]
@sselph I won't be able to test on my end for a few days.  I'll report back as soon as possible.  Thank you!

**Comment by stevetb** [comment]
@paradadf Did they add any new titles from the list I put up a few weeks ago?  If so, I can add the titles to TGDB which are missing and make another .CSV for sselph.

**Comment by paradadf** [comment]
@stevetb no need for that. They just updated two games and the hash changed, but now all roms from your list and the two updated are being scraped! Thank you both Steves!

**Comment by stevetb** [comment]
@sselph Thank you!  This looks great.  I will close this and mark as completed.
