### ISSUE TITLE
Add Support for Nintendo Famicom Disc System

### ISSUE THREAD

**Issue by InsecureSpike** [sselph/scraper#95]
could you please add support for Nintendo Favicon Disc System

https://github.com/RetroPie/RetroPie-Setup/pull/1531

thank you

**Comment by stevetb** [comment]
I don't believe this is supported yet on the Retropie, which from your link appears to be the system you are interested in.  Support should be easy though to add to the sselph scraper.  

What is the file extension for the games?

**Comment by InsecureSpike** [comment]
hi, it's .fds, thank you

**Comment by stevetb** [comment]
@InsecureSpike So it looks like this platform is on TheGamesDB so most titles are all set.  Do you have this running on a RetroPie?  If it works, I can help match the TGDB to file hashes.  It's a pretty small set overall.  

@sselph please add .FDS as a supported file extension

**Comment by InsecureSpike** [comment]
awesome, thsnks, we've just moved so no pi's set up yet, fingers crossed for Wednesday! then I can test
thanks

**Comment by InsecureSpike** [comment]
ok, my pi is up & running, but still can't scrape .fds

**cd /home/pi/RetroPie/roms/fds
/opt/retropie/supplementary/scraper/scraper -use_gdb=true  -use_nointro_name=true -add_not_found=true -use_filename=true -download_images=true**

**Comment by InsecureSpike** [comment]
2016/07/07 10:17:42 INFO: hash.csv "94a1dd9563ca555428e9d9cce3454d08" up to date.

**Comment by stevetb** [comment]
@InsecureSpike sorry about that.  We are waiting for @sselph.  Since it is summer time I'll bet he has a lot going on.  He will pop on and add this extension soon I'd bet.

Once he adds this, I think we are all set to start building the TGDB to Hash links.  That should only take a night or two to complete.

**Comment by InsecureSpike** [comment]
no need to be sorry, I was just relaying info back, mate
thank you, for the heads up

**Comment by stevetb** [comment]
I'm looking forward to doing this, it will be fun!

**Comment by sselph** [comment]
I added FDS support and the existing 75 thegamedb entries matched up to ~90 of the ~300 no-intro entries.

**Comment by InsecureSpike** [comment]
awesome thanks guys, I'll give it a go laters

**Comment by InsecureSpike** [comment]
do i have to update the scraper, for this to work?

**Comment by sselph** [comment]
Yes or since this is a simple hash you can do `-extra_ext=".fds"` to force it to look at those files.

**Comment by InsecureSpike** [comment]
awesome will try after work, thanks

**Comment by InsecureSpike** [comment]
that's awesome! thank you guys! 
all works well
